### ISSUE TITLE
GenerateShares step fails if an account has no tags

### ISSUE THREAD

**Issue by michael-dickinson-sainsburys** [awslabs/aws-service-catalog-puppet#132]
When an account is defined in the `manifest.yaml` without a tags section, then the GenerateShares step of the pipeline fails in CodeBuild with the following stack trace:
```
Traceback (most recent call last): 
  File "/usr/local/bin/servicecatalog-puppet", line 11, in <module> 
    sys.exit(cli()) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__ 
    return self.main(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main 
    rv = self.invoke(ctx) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke 
    return _process_result(sub_ctx.command.invoke(sub_ctx)) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke 
    return callback(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 21, in generate_shares 
    cli_commands.generate_shares(f) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_commands.py", line 52, in generate_shares 
    deployment_map = manifest_utils.build_deployment_map(manifest, constants.LAUNCHES) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/manifest_utils.py", line 78, in build_deployment_map 
    section 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/manifest_utils.py", line 56, in generate_launch_map 
    for tag in account.get('tags'): 
TypeError: 'NoneType' object is not iterable 
```

**Comment by eamonnfaherty** [comment]
fixed in 0.27.0

Thanks for raising (and fixing)
