### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by michael-dickinson-sainsburys** [awslabs/aws-service-catalog-puppet#134]
The documentation doesn't provide examples of sharing or launching products in all of the regions in the `regions_enabled` list. The natural choice for the `regions` value would be `regions_enabled`, however, this breaks the 'Deploy' phase with the following stack trace:
```
Traceback (most recent call last): 
  File "/usr/local/bin/servicecatalog-puppet", line 11, in <module> 
    sys.exit(cli()) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__ 
    return self.main(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main 
    rv = self.invoke(ctx) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke 
    return _process_result(sub_ctx.command.invoke(sub_ctx)) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke 
    return callback(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 28, in deploy 
    cli_commands.deploy(f, single_account) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_commands.py", line 132, in deploy 
    spoke_local_portfolio_tasks_to_run = cli_command_helpers.deploy_spoke_local_portfolios(manifest, launch_tasks) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_command_helpers.py", line 450, in deploy_spoke_local_portfolios 
    deployment_map = set_regions_for_deployment_map(deployment_map, section) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_command_helpers.py", line 166, in set_regions_for_deployment_map 
    raise Exception("Unknown regions: {}".format(regions)) 
Exception: Unknown regions: regions_enabled 
```

The correct value for the `regions` key should be `enabled`.

**Comment by eamonnfaherty** [comment]
Previously only enabled was allowed.  I have added regions_enabled as a valid option and I have updated the docs.

Sorry for the gap here.
