### ISSUE TITLE
Suspended Orgs account causes manifest expand to fail

### ISSUE THREAD

**Issue by jasonsteenblik** [awslabs/aws-service-catalog-puppet#140]
```
Traceback (most recent call last):
  File "/Code/aws-service-catalog-factory/venv/bin/servicecatalog-puppet", line 10, in <module>
    sys.exit(cli())
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 80, in expand
    cli_commands.expand(f)
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/servicecatalog_puppet/cli_commands.py", line 327, in expand
    new_manifest = manifest_utils.expand_manifest(manifest, client)
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/servicecatalog_puppet/manifest_utils.py", line 102, in expand_manifest
    new_accounts += expand_path(account, client)
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/servicecatalog_puppet/manifest_utils.py", line 153, in expand_path
    return expand_ou(account, client)
  File "/Code/aws-service-catalog-factory/venv/lib/python3.7/site-packages/servicecatalog_puppet/manifest_utils.py", line 173, in expand_ou
    logger.info(f"Skipping account as it is not ACTIVE: {json.dump(response.get('Account'), default=str)}")
TypeError: dump() missing 1 required positional argument: 'fp'
~
```

**Comment by eamonnfaherty** [comment]
fixed and released
