### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#149]
We've started seeing the below error during some of our Puppet runs:

```
Traceback (most recent call last): 
File "/usr/local/bin/servicecatalog-puppet", line 11, in <module> 
sys.exit(cli()) 
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__ 
return self.main(*args, **kwargs) 
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main 
rv = self.invoke(ctx) 
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke 
return _process_result(sub_ctx.command.invoke(sub_ctx)) 
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke 
return ctx.invoke(self.callback, **ctx.params) 
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke 
return callback(*args, **kwargs) 
File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 28, in deploy 
cli_commands.deploy(f, single_account) 
File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_commands.py", line 135, in deploy 
cli_command_helpers.run_tasks(tasks_to_run) 
File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_command_helpers.py", line 633, in run_tasks 
log_level='INFO', 
File "/usr/local/lib/python3.7/site-packages/luigi/interface.py", line 237, in build 
luigi_run_result = _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params) 
File "/usr/local/lib/python3.7/site-packages/luigi/interface.py", line 173, in _schedule_and_run 
success &= worker.run() 
File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 1202, in run 
self._run_task(get_work_response.task_id) 
File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 1004, in _run_task 
task_process.start() 
File "/usr/local/lib/python3.7/multiprocessing/process.py", line 112, in start 
self._popen = self._Popen(self) 
File "/usr/local/lib/python3.7/multiprocessing/context.py", line 223, in _Popen 
return _default_context.get_context().Process._Popen(process_obj) 
File "/usr/local/lib/python3.7/multiprocessing/context.py", line 277, in _Popen 
return Popen(process_obj) 
File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__ 
self._launch(process_obj) 
File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch 
self.pid = os.fork() 
OSError: [Errno 12] Cannot allocate memory
```

This is even after we've set the CodeBuild job to use the 4CPU / 7GB memory container type.

**Comment by eamonnfaherty** [comment]
Thanks for the report @jordan-evans 

How often are you seeing this?

**Comment by eamonnfaherty** [comment]
which version of puppet does your stack trace come from?

**Comment by jordan-evans** [comment]
Not very often, but we've bumped the container size up to the maximum now.

Puppet version is `0.32.0`

**Comment by jordan-evans** [comment]
Still happening on `0.39.0`. Using the maximum container size so nowhere else to go now :(

**Comment by deswalnaveen** [comment]
Use below, logstast start automatically after puppy agent -t command

systemctl stop logstash

This should resolve your issue.
