### ISSUE TITLE
CloudFormation Internal Error after importing product 

### ISSUE THREAD

**Issue by beataa** [awslabs/aws-service-catalog-puppet#151]
Hello,

I am not able to launch following product into spoke account.
product.template.yaml:

```
AWSTemplateFormatVersion: 2010-09-09   
Description: Event Bus
 
Parameters: 
   ORGID:   
     Type: String   
     Description: The AWS Organizations ID example o-xxxxxxx 
   
 
Resources: 
 
  DefaultEventBusPolicy:  
    Type: AWS::Events::EventBusPolicy 
    Properties:  
        Action: "events:PutEvents" 
        Principal: "*" 
        StatementId: "SendEventsStatement" 
        Condition:  
            Type: "StringEquals" 
            Key: "aws:PrincipalOrgID" 
            Value: !Ref ORGID 
 
  CloudWatchEventTopic:   
    Type: AWS::SNS::Topic  
    Properties:  
      DisplayName: CloudWatchEventTopic  
      TopicName: CloudWatchEventTopic  
       
       
  CloudWatchEventPolicy:  
    Type: AWS::SNS::TopicPolicy 
    Properties:  
      Topics:  
        - !Ref CloudWatchEventTopic  
      PolicyDocument:  
        Version: 2012-10-17  
        Statement:  
          - Action: 'sns:Publish'  
            Sid: '01'  
            Resource: !Ref CloudWatchEventTopic  
            Effect: Allow  
            Principal:  
              AWS:  
                - '*'  
            Condition:    
                StringEquals:    
                  aws:PrincipalOrgID:    
                    - !Ref ORGID  
          - Action: 'sns:Subscribe'   
            Sid: '2'   
            Effect: Allow   
            Resource: !Ref CloudWatchEventTopic   
            Principal:   
              AWS:   
               - !Sub arn:aws:iam::${AWS::AccountId}:root  
               - !Sub arn:aws:iam::${AWS::AccountId}:role/servicecatalog-puppet/PuppetRole  
      
    
  CloudWatchEventTopicARN:  
    Type: AWS::SSM::Parameter    
    Description: |    
      Outputs CloudWatchEvent Top ARN ```SFC-CloudWatchEventTopicARN```    
    DependsOn:    
      - CloudWatchEventTopic    
    Properties:    
      Name: SFC-CloudWatchEventTopicARN   
      Type: String    
      Value: !Ref CloudWatchEventTopic   
   
  #Subscription in Security Account for CloudWatch Event rules     
  SNSCloudWatchSubscription:  
    Type: AWS::SNS::Subscription  
    Properties:  
      TopicArn: !Ref 'CloudWatchEventTopic'  
      Protocol: email  
      Endpoint: mail@somemail.com  
```     

When I run this template with CloudFormation (without Puppet) it result with success.
When I use puppet - it fails.

Template after puppet import looks like this:

```
'AWSTemplateFormatVersion': '2010-09-09'
'Description': 'Enable Event Bus'
'Parameters':
  'ORGID':
    'Type': 'String'
    'Description': 'The AWS Organizations ID example o-xxxxxxx'
'Resources':
  'DefaultEventBusPolicy':
    'Type': 'AWS::Events::EventBusPolicy'
    'Properties':
      'Action': 'events:PutEvents'
      'Principal': '*'
      'StatementId': 'SendEventsStatement'
      'Condition':
        'Type': 'StringEquals'
        'Key': 'aws:PrincipalOrgID'
        'Value':
          'Ref': 'ORGID'
  'CloudWatchEventTopic':
    'Type': 'AWS::SNS::Topic'
    'Properties':
      'DisplayName': 'CloudWatchEventTopic'
      'TopicName': 'CloudWatchEventTopic'
  'CloudWatchEventPolicy':
    'Type': 'AWS::SNS::TopicPolicy'
    'Properties':
      'Topics':
      - 'Ref': 'CloudWatchEventTopic'
      'PolicyDocument':
        'Version': '2012-10-17'
        'Statement':
        - 'Action': 'sns:Publish'
          'Sid': '01'
          'Resource':
            'Ref': 'CloudWatchEventTopic'
          'Effect': 'Allow'
          'Principal':
            'AWS':
            - '*'
          'Condition':
            'StringEquals':
              'aws:PrincipalOrgID':
              - 'Ref': 'ORGID'
        - 'Action': 'sns:Subscribe'
          'Sid': '2'
          'Effect': 'Allow'
          'Resource':
            'Ref': 'CloudWatchEventTopic'
          'Principal':
            'AWS':
            - 'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:root'
            - 'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:role/servicecatalog-puppet/PuppetRole'
  'CloudWatchEventTopicARN':
    'Type': 'AWS::SSM::Parameter'
    'Description': "Outputs CloudWatchEvent Top ARN ```SFC-CloudWatchEventTopicARN```\
      \   \n"
    'DependsOn':
    - 'CloudWatchEventTopic'
    'Properties':
      'Name': 'SFC-CloudWatchEventTopicARN'
      'Type': 'String'
      'Value':
        'Ref': 'CloudWatchEventTopic'
  'SNSCloudWatchSubscription':
    'Type': 'AWS::SNS::Subscription'
    'Properties':
      'TopicArn':
        'Ref': 'CloudWatchEventTopic'
      'Protocol': 'email'
      'Endpoint': 'mail@somemail.com'
'Rules': {}

```
At the very end there is 'Rules: {}'  empty statement added. 
Perhaps its because of this..

Puppet manifest file part:

  #CloudWatch Event bus  
  cloudwatch-eventbus:      
    portfolio: avm-monitoring-baseline      
    product: cloudwatch-eventbus     
    version: v1    
    deploy_to:      
      tags:      
        - tag: is-security:true      
          regions: default_region    

Looking forward for any hints..

Beata

**Comment by eamonnfaherty** [comment]
Could I see your error message please.

From what I can see your tag definition may cause an issue.  tags should be a list of strings.  from what I can see of your tags I think it may be read as a dict instead.  If you share your error message I will know for sure.

You can try:
```yaml
cloudwatch-eventbus:
  portfolio: avm-monitoring-baseline
  product: cloudwatch-eventbus
  version: v1
  deploy_to:
    tags:
      - tag: 'is-security:true'
         regions: default_region
```
You would also need to change the tags on your account section.

**Comment by beataa** [comment]
I am using same way of defining tags with other products without issue.
Here is another example:
  IdentityProvider-SAML-Shared:   
    portfolio: avm-sso-baseline   
    product: idp-saml-shared   
    version: v1   
    deploy_to:   
      tags:   
        - tag: type:ip   
          regions: default_region  
        - tag: is-security:true      
          regions: default_region     
        - tag: is-master:true      
          regions: default_region 
        - tag: is-central-log:true      
          regions: default_region 
        - tag: is-hub:true 
          regions: default_region   


Product stays in PLAN_IN_PROGRESS/ REVIEW_IN_PROGRESS state, the only indication or error in Service Catalog in target account is on ChangeSet: 
   Status reason
   Internal Failure

On puppet level: 

```
INFO MainThread [cloudwatch-eventbus5] account_id:eu-central-1] :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [cloudwatch-eventbus5] account_id:eu-central-1] :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [cloudwatch-eventbus5] account_id:eu-central-1] :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [cloudwatch-eventbus5] account_id:eu-central-1] :: Waiting for product plan: CREATE_FAILED 
ERROR: [pid 149] Worker Worker(salt=988486853, workers=10, host=5f039703d8f0, username=root, pid=98) failed    ProvisionProductTask(launch_name=cloudwatch-eventbus5, portfolio=avm-monitoring-baseline, product=cloudwatch-eventbus, version=v1, product_id=prod-fiamtdyozxf42, version_id=pa-fts64avlrhew2, account_id=account_id, region=eu-central-1, puppet_account_id=puppet_account_id, parameters=[{"name": "ORGID", "value": "org_id"}], ssm_param_inputs=[], retry_count=1, ssm_param_outputs=[]) 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run 
    new_deps = self._run_get_new_deps() 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps 
    task_gen = self.task.run() 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 251, in run 
    self.version, 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 224, in provision_product 
    raise Exception(f"{uid} :: Plan failed: {response.get('ProvisionedProductPlanDetails').get('StatusMessage')}") 
Exception: [cloudwatch-eventbus5] 245204761060:eu-central-1] :: Plan failed: Internal Failure 
ERROR MainThread [pid 149] Worker Worker(salt=988486853, workers=10, host=5f039703d8f0, username=root, pid=98) failed    ProvisionProductTask(launch_name=cloudwatch-eventbus5, portfolio=avm-monitoring-baseline, product=cloudwatch-eventbus, version=v1, product_id=prod-fiamtdyozxf42, version_id=pa-fts64avlrhew2, account_id=account_id, region=eu-central-1, puppet_account_id=pupet_account_id, parameters=[{"name": "ORGID", "value": "org_id"}], ssm_param_inputs=[], retry_count=1, ssm_param_outputs=[]) 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run 
    new_deps = self._run_get_new_deps() 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps 
    task_gen = self.task.run() 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 251, in run 
    self.version, 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 224, in provision_product 
    raise Exception(f"{uid} :: Plan failed: {response.get('ProvisionedProductPlanDetails').get('StatusMessage')}") 
Exception: [cloudwatch-eventbus5] 245204761060:eu-central-1] :: Plan failed: Internal Failure 
INFO: Informed scheduler that task   ProvisionProductTask_245204761060_cloudwatch_event____name____ORGID_3d9b4b54a3   has status   FAILED 
INFO MainThread Informed scheduler that task   ProvisionProductTask_245204761060_cloudwatch_event____name____ORGID_3d9b4b54a3   has status   FAILED 

```

When you run template directly it runs with success, so something is changed with puppet > Service Catalog product..

We have 20+ products only this one fails - why?

**Comment by beataa** [comment]
Bug reported on AWS CLoudFormation for EventBus Policy having Conditions.
`'DefaultEventBusPolicy':
    'Type': 'AWS::Events::EventBusPolicy'
    'Properties':
      'Action': 'events:PutEvents'
      'Principal': '*'
      'StatementId': 'SendEventsStatement'
      'Condition':
        'Type': 'StringEquals'
        'Key': 'aws:PrincipalOrgID'
        'Value':
          'Ref': 'ORGID'`


I solve the problem by using Lambda and creating this policy with AWS SDK.

Issue reported here:  https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/156

**Comment by eamonnfaherty** [comment]
Thanks for identifying this.  I will mark it as closed here as it isn't an issue with this project.
