### ISSUE TITLE
EventBridge PutEvent limit

### ISSUE THREAD

**Issue by atoa** [awslabs/aws-service-catalog-puppet#166]
In version 0.35.0, with config `should_forward_events_to_eventbridge: true`, you can hit a limit in the PutEvents API call. There is a limit of 10 entries in PutEvents. See: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/cloudwatch_limits_cwe.html

Here's a stack trace:

```
INFO MainThread Sending 11 events to eventbridge 
Traceback (most recent call last): 
  File "/usr/local/bin/servicecatalog-puppet", line 11, in <module> 
    sys.exit(cli()) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__ 
    return self.main(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main 
    rv = self.invoke(ctx) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke 
    return _process_result(sub_ctx.command.invoke(sub_ctx)) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke 
    return callback(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 28, in deploy 
    cli_commands.deploy(f, single_account) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_commands.py", line 140, in deploy 
    cli_command_helpers.run_tasks(tasks_to_run) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_command_helpers.py", line 764, in run_tasks 
    events.put_events(Entries=entries) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutEvents operation: 1 validation error detected: Value '[com.amazon.jetstream.v20151007.PutEventsRequestEntry@613c8532, com.amazon.jetstream.v20151007.PutEventsRequestEntry@9319abad, com.amazon.jetstream.v20151007.PutEventsRequestEntry@3ad8b5b8, com.amazon.jetstream.v20151007.PutEventsRequestEntry@1b796fb7, com.amazon.jetstream.v20151007.PutEventsRequestEntry@4dbbb227, com.amazon.jetstream.v20151007.PutEventsRequestEntry@56e73b6e, com.amazon.jetstream.v20151007.PutEventsRequestEntry@4aa32c33, com.amazon.jetstream.v20151007.PutEventsRequestEntry@e01c73f7, com.amazon.jetstream.v20151007.PutEventsRequestEntry@201c5660, com.amazon.jetstream.v20151007.PutEventsRequestEntry@6d338f20, com.amazon.jetstream.v20151007.PutEventsRequestEntry@81598085]' at 'entries' failed to satisfy constraint: Member must have length less than or equal to 10 
```

**Comment by eamonnfaherty** [comment]
Testing a fix for this now.
