### ISSUE TITLE
Puppet Error on Generate Shares

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#181]
Getting the below error in my CodeBuild job for the generation of shares.

Tested on `0.42.0` & reproduced on `0.44.1`

```
===== Luigi Execution Summary ===== 
 
Scheduled 647 tasks of which: 
* 647 ran successfully: 
    ... 
 
This progress looks :) because there were no failed tasks or missing dependencies 
 
===== Luigi Execution Summary ===== 
 
INFO MainThread getting should_use_sns,  default_region: None 
INFO MainThread getting config,  default_region: None 
Traceback (most recent call last): 
  File "/usr/local/bin/servicecatalog-puppet", line 11, in <module> 
    sys.exit(cli()) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__ 
    return self.main(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main 
    rv = self.invoke(ctx) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke 
    return _process_result(sub_ctx.command.invoke(sub_ctx)) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke 
    return callback(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 21, in generate_shares 
    cli_commands.generate_shares(f) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_commands.py", line 76, in generate_shares 
    cli_command_helpers.run_tasks_for_generate_shares(tasks_to_run) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_command_helpers.py", line 822, in run_tasks_for_generate_shares 
    version = get_puppet_version() 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_command_helpers.py", line 278, in get_puppet_version 
    return pkg_resources.require("aws-service-catalog-puppet")[0].version 
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require 
    needed = self.resolve(parse_requirements(requirements)) 
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve 
    raise VersionConflict(dist, req).with_context(dependent_req) 
pkg_resources.ContextualVersionConflict: (python-dateutil 2.8.1 (/usr/local/lib/python3.7/site-packages), Requirement.parse('python-dateutil<2.8.1,>=2.1; python_version >= "2.7"'), {'botocore'})  ```

**Comment by eamonnfaherty** [comment]
This looks like an issue with a transient dependency not being pinned.  I will take a look now

**Comment by eamonnfaherty** [comment]
0.44.2 is a tactical / quick fix for this.  I am going to switch the project over to pipenv to reduce the risk of this happening in the future.
