### ISSUE TITLE
OpsCenter truncating the logs from Puppet exceptions

### ISSUE THREAD

**Issue by smuralee** [awslabs/aws-service-catalog-puppet#212]
**Issue**
OpsCenter is truncating the logs and the root cause is not visible in the description

**Current Description in OpsCenter**
`
Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run new_deps = self._run_get_new_deps() File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 150, in _run_get_new_deps requires = six.next(task_gen) File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 644, in run self.should_use_sns, File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 283, in provision_product raise Exception(f"{uid} :: Execute failed: {execute_status}: {provisioned_product_detail.get('StatusMessage')}") Exception: [experiments] 123456789012:us-east-2] :: Execute failed: ERROR: CloudFormation stack creation failed. Errors from CloudFormation: [{LogicalResourceId : SC-123456789012-pp-gvn72phz5h2he, ResourceType : AWS::CloudFormation::Stack, StatusReason : The following resource(s) failed to create: [LogsBucket, PrintLambdaRole, AppDevRole]. . Rollback requested by
`

**Expected Description in OpsCenter**
`
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run 
    new_deps = self._run_get_new_deps() 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 150, in _run_get_new_deps 
    requires = six.next(task_gen) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 644, in run 
    self.should_use_sns, 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 283, in provision_product 
    raise Exception(f"{uid} :: Execute failed: {execute_status}: {provisioned_product_detail.get('StatusMessage')}") 
Exception: [experiments] 123456789012:us-east-2] :: Execute failed: ERROR: CloudFormation stack creation failed. Errors from CloudFormation: [{LogicalResourceId : SC-123456789012-pp-wmbqukrakudym, ResourceType : AWS::CloudFormation::Stack, StatusReason : The following resource(s) failed to create: [LogsBucket, PrintLambdaRole, AppDevRole]. . Rollback requested by user.}, {LogicalResourceId : LogsBucket, ResourceType : AWS::S3::Bucket, StatusReason : Resource creation cancelled}, {LogicalResourceId : PrintLambdaRole, ResourceType : AWS::IAM::Role, StatusReason : Resource creation cancelled}, {LogicalResourceId : AppDevRole, ResourceType : AWS::IAM::Role, StatusReason : Invalid principal in policy: "AWS":"arn:aws:iam::123456789012:role/TagBasedAccess" (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 329c11c2-7671-477b-9bf9-96a5138ade7e)}] 
`

**Comment by eamonnfaherty** [comment]
we now post the last 1024 chars and not the first.  

the limit for opscenter opsitems descriptions is 1024 chars.

if this is not good enough please reopen and I will look at adding a deep link into cloudwatch logs
