### ISSUE TITLE
First puppet run fails

### ISSUE THREAD

**Issue by ajoga** [awslabs/aws-service-catalog-puppet#216]
Hello, 

I installed today my factory & my puppet within the same account using the cloudformation initializers. 

I bootstraped a spoke account with `servicecatalog-puppet bootstrap-spoke <ACCOUNT_ID_OF_YOUR_PUPPET>`

I just added my spoke to the manifest of the puppet : 

```
accounts: 
  - account_id: "XXXredactedXXX" 
    name: "XXXredactedXXX" 
    default_region: "eu-west-1" 
    regions_enabled: 
      - "eu-west-1" 
    tags: 
      - "type:pocprod" 
spoke-local-portfolios: 
  XXXredactedXXX: 
    portfolio: XXXredactedXXX 
    deploy_to: 
      tags: 
        - tag: "type:pocprod" 
          regions: all 
``` 

The `servicecatalog-puppet-pipeline` pipeline fails with these logs in the Codebuild : 

```
[Container] 2019/11/26 16:53:41 Running command servicecatalog-puppet --info expand manifest.yaml 
Expanding 
Traceback (most recent call last): 
  File "/usr/local/bin/servicecatalog-puppet", line 11, in <module> 
    sys.exit(cli()) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__ 
    return self.main(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main 
    rv = self.invoke(ctx) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke 
    return _process_result(sub_ctx.command.invoke(sub_ctx)) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke 
    return callback(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 100, in expand 
    core.expand(f) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/core.py", line 530, in expand 
    org_iam_role_arn = config.get_org_iam_role_arn() 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/config.py", line 68, in get_org_iam_role_arn 
    response = ssm.get_parameter(Name=constants.CONFIG_PARAM_NAME_ORG_IAM_ROLE_ARN) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation:  
 
[Container] 2019/11/26 16:53:42 Command did not exit successfully servicecatalog-puppet --info expand manifest.yaml exit status 1 
[Container] 2019/11/26 16:53:42 Phase complete: BUILD State: FAILED 
[Container] 2019/11/26 16:53:42 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-puppet --info expand manifest.yaml. Reason: exit status 1 
[Container] 2019/11/26 16:53:42 Entering phase POST_BUILD 
[Container] 2019/11/26 16:53:42 Phase complete: POST_BUILD State: SUCCEEDED 
[Container] 2019/11/26 16:53:42 Phase context status code:  Message:  
[Container] 2019/11/26 16:53:42 Expanding base directory path: . 
[Container] 2019/11/26 16:53:42 Assembling file list 
[Container] 2019/11/26 16:53:42 Expanding . 
[Container] 2019/11/26 16:53:42 Expanding file paths for base directory . 
[Container] 2019/11/26 16:53:42 Assembling file list 
[Container] 2019/11/26 16:53:42 Expanding manifest-expanded.yaml 
[Container] 2019/11/26 16:53:42 Skipping invalid file path manifest-expanded.yaml 
[Container] 2019/11/26 16:53:42 Expanding data/*/*/*/*.json 
[Container] 2019/11/26 16:53:42 Expanding shares/*/*/*.json 
[Container] 2019/11/26 16:53:42 Expanding topic/*/*/*.json 
[Container] 2019/11/26 16:53:42 Phase complete: UPLOAD_ARTIFACTS State: FAILED 
[Container] 2019/11/26 16:53:42 Phase context status code: CLIENT_ERROR Message: no matching artifact paths found 
``` 

Did I miss something for the provisioning ? I'm going to dig a bit to understand how to get past this regardless. 

Thanks

**Comment by ajoga** [comment]
Okay with the help of @VictorRaim I noticed that you already pushed a fix in the release [0.56.2](https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.56.2) :) 

Since I followed the workshop doc to install this project, I used the CloudFormation initializer. The [upgrading](https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/upgrading.html) documentation could use some updating... May I offer help here ? How would you like to move ahead ?

**Comment by ajoga** [comment]
@eamonnfaherty With the setup described earlier (i.e share between two accounts, no usage of organization), I encounter the following error at the build stage for the puppet : 

```
INFO: Running Worker with 10 processes 
INFO MainThread Running Worker with 10 processes 
INFO: [pid 106] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) running   RequestPolicyTask(type=topic, region=eu-west-1, account_id=AWS_ACCOUNT_ID_SPOKE, organization=None) 
INFO MainThread [pid 106] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) running   RequestPolicyTask(type=topic, region=eu-west-1, account_id=AWS_ACCOUNT_ID_SPOKE, organization=None) 
INFO: [pid 106] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) done      RequestPolicyTask(type=topic, region=eu-west-1, account_id=AWS_ACCOUNT_ID_SPOKE, organization=None) 
INFO MainThread [pid 106] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) done      RequestPolicyTask(type=topic, region=eu-west-1, account_id=AWS_ACCOUNT_ID_SPOKE, organization=None) 
INFO: [pid 107] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) running   ShareAndAcceptPortfolioTask(account_id=AWS_ACCOUNT_ID_SPOKE, region=eu-west-1, portfolio=XXXX_PORTFOLIO_NAME_XXXX, puppet_account_id=AWS_ACCOUNT_ID_HUB) 
INFO MainThread [pid 107] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) running   ShareAndAcceptPortfolioTask(account_id=AWS_ACCOUNT_ID_SPOKE, region=eu-west-1, portfolio=XXXX_PORTFOLIO_NAME_XXXX, puppet_account_id=AWS_ACCOUNT_ID_HUB) 
INFO: Informed scheduler that task   RequestPolicyTask_AWS_ACCOUNT_ID_SPOKE_None_eu_west_1_699dec4951   has status   DONE 
INFO MainThread Informed scheduler that task   RequestPolicyTask_AWS_ACCOUNT_ID_SPOKE_None_eu_west_1_699dec4951   has status   DONE 
INFO MainThread ShareAndAcceptPortfolioTask/AWS_ACCOUNT_ID_SPOKE--eu-west-1--XXXX_PORTFOLIO_NAME_XXXX starting ShareAndAcceptPortfolioTask 
INFO MainThread Getting portfolio id for: XXXX_PORTFOLIO_NAME_XXXX 
INFO: [pid 109] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) running   RequestPolicyTask(type=bucket, region=eu-west-1, account_id=AWS_ACCOUNT_ID_SPOKE, organization=None) 
INFO MainThread [pid 109] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) running   RequestPolicyTask(type=bucket, region=eu-west-1, account_id=AWS_ACCOUNT_ID_SPOKE, organization=None) 
INFO: [pid 109] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) done      RequestPolicyTask(type=bucket, region=eu-west-1, account_id=AWS_ACCOUNT_ID_SPOKE, organization=None) 
INFO MainThread [pid 109] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) done      RequestPolicyTask(type=bucket, region=eu-west-1, account_id=AWS_ACCOUNT_ID_SPOKE, organization=None) 
INFO: Informed scheduler that task   RequestPolicyTask_AWS_ACCOUNT_ID_SPOKE_None_eu_west_1_e9dbfc5a5f   has status   DONE 
INFO MainThread Informed scheduler that task   RequestPolicyTask_AWS_ACCOUNT_ID_SPOKE_None_eu_west_1_e9dbfc5a5f   has status   DONE 
INFO MainThread Found portfolio: {'Id': 'port-xxxportfolioidxxx', 'ARN': 'arn:aws:catalog:eu-west-1:AWS_ACCOUNT_ID_HUB:portfolio/port-xxxportfolioidxxx', 'DisplayName': 'XXXX_PORTFOLIO_NAME_XXXX', 'Description': 'XXXX products', 'CreatedTime': datetime.datetime(2019, 11, 26, 15, 54, 49, 583000, tzinfo=tzlocal()), 'ProviderName': 'XXXX BO'} 
INFO MainThread ShareAndAcceptPortfolioTask/AWS_ACCOUNT_ID_SPOKE--eu-west-1--XXXX_PORTFOLIO_NAME_XXXX: checking port-xxxportfolioidxxx with AWS_ACCOUNT_ID_SPOKE 
INFO MainThread ShareAndAcceptPortfolioTask/AWS_ACCOUNT_ID_SPOKE--eu-west-1--XXXX_PORTFOLIO_NAME_XXXX: sharing port-xxxportfolioidxxx with AWS_ACCOUNT_ID_SPOKE 
INFO MainThread list_accepted_portfolio_shares: {} 
INFO MainThread searching, PageToken: FirstPage 
INFO MainThread ShareAndAcceptPortfolioTask/AWS_ACCOUNT_ID_SPOKE--eu-west-1--XXXX_PORTFOLIO_NAME_XXXX: accepting port-xxxportfolioidxxx 
ERROR: [pid 107] Worker Worker(salt=320512351, workers=10, host=1e43df888318, username=root, pid=102) failed    ShareAndAcceptPortfolioTask(account_id=AWS_ACCOUNT_ID_SPOKE, region=eu-west-1, portfolio=XXXX_PORTFOLIO_NAME_XXXX, puppet_account_id=AWS_ACCOUNT_ID_HUB) 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run 
    new_deps = self._run_get_new_deps() 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps 
    task_gen = self.task.run() 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/workflow/portfoliomanagement.py", line 855, in run 
    PortfolioId=portfolio_id, 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the AcceptPortfolioShare operation: Portfolio port-xxxportfolioidxxx not found. 
``` 

If I manually share the portfolio to my spoke account, then a rerun works. 

I am not comfortable in big python projects, but it seems that there is some missing logic to handle the sharing of the portfolio from the hub to the spoke if it's not done yet : https://github.com/awslabs/aws-service-catalog-puppet/blob/master/servicecatalog_puppet/workflow/portfoliomanagement.py#L836

**Comment by eamonnfaherty** [comment]
this is now fixed

**Comment by eamonnfaherty** [comment]
Thanks for reporting it and for pointing out where the issue was.
