### ISSUE TITLE
Changing a SC-F product with something that won't trigger a change plan causes an exception.

### ISSUE THREAD

**Issue by nikolaigauss** [awslabs/aws-service-catalog-puppet#241]
### Behaviour Seen
Puppet fails to provision a product when only the description in the CFN template is modified. 

**From Puppet Log**

```
ProvisionProductTask failed
--
508 | parameters:
509 | account_id: '109780043335'
510 | account_parameters: <FrozenOrderedDict OrderedDict()>
511 | dependencies: []
512 | launch_name: all-cloudtrail-enable
513 | launch_parameters: <FrozenOrderedDict OrderedDict()>
514 | manifest_parameters: <FrozenOrderedDict OrderedDict([('AWSOrganisationID', <FrozenOrderedDict
515 | OrderedDict([('default', 'o-hdlxtom0dp')])>), ('CentralCloudTrailBucket', <FrozenOrderedDict
516 | OrderedDict([('default', 'centralised-logs-170194364726-eu-west-1')])>), ('CentralConfigBucket',
517 | <FrozenOrderedDict OrderedDict([('default', 'centralised-logs-170194364726-eu-west-1')])>),
518 | ('DeploymentAccountId', <FrozenOrderedDict OrderedDict([('default', '449782587015')])>),
519 | ('GuardDutyAssumableOrgRoleArn', <FrozenOrderedDict OrderedDict([('default', 'arn:aws:iam::178759752866:role/guardduty/GuarDutyAssumableRoleInRootAccount')])>),
520 | ('HubAccountID', <FrozenOrderedDict OrderedDict([('default', '881518331318')])>),
521 | ('HubEnablerFunctionRole', <FrozenOrderedDict OrderedDict([('default', 'arn:aws:iam::881518331318:role/GuardDutyHubRole')])>),
522 | ('LoggingAccountId', <FrozenOrderedDict OrderedDict([('default', '170194364726')])>),
523 | ('MasterAccountId', <FrozenOrderedDict OrderedDict([('default', '178759752866')])>),
524 | ('NetworkAccountId', <FrozenOrderedDict OrderedDict([('default', '280450906216')])>),
525 | ('SSHKeyName', <FrozenOrderedDict OrderedDict([('default', 'SquishyBottom')])>),
526 | ('SecurityAccountId', <FrozenOrderedDict OrderedDict([('default', '881518331318')])>)])>
527 | parameters: []
528 | portfolio: oss-catalog-factory-mandatory-product-portfolio
529 | post_actions: []
530 | pre_actions: []
531 | product: Cloudtrail-Enable
532 | puppet_account_id: '449782587015'
533 | region: eu-west-1
534 | requested_priority: 0
535 | retry_count: 0
536 | should_use_product_plans: true
537 | should_use_sns: true
538 | ssm_param_inputs: []
539 | ssm_param_outputs: []
540 | version: v1
541 | worker_timeout: 0
542 |  
543 | Traceback (most recent call last):
544 |  
545 | File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
546 | new_deps = self._run_get_new_deps()
547 |  
548 | File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 150, in _run_get_new_deps
549 | requires = six.next(task_gen)
550 |  
551 | File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/workflow/provisioning.py", line 309, in run
552 | self.should_use_sns,
553 |  
554 | File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 230, in provision_product_with_plan
555 | raise Exception(f"{uid} :: Plan failed: {response.get('ProvisionedProductPlanDetails').get('StatusMessage')}")
556 |  
557 | Exception: [all-cloudtrail-enable] 109780043335:eu-west-1] :: Plan failed: The submitted information didn't contain changes. Submit different information to create a change set.


```

### Expected Behaviour
Puppet should update the CFN template on the specified accounts with the updated description

### Observations
If after the event mentioned before, a significant changed is added, such as adding a new resource in the CFN template this error will be shown:

```
ProvisionProductTask failed
508 | parameters:
509 | account_id: '109780043335'
510 | account_parameters: <FrozenOrderedDict OrderedDict()>
511 | dependencies: []
512 | launch_name: all-cloudtrail-enable
513 | launch_parameters: <FrozenOrderedDict OrderedDict()>
514 | manifest_parameters: <FrozenOrderedDict OrderedDict([('AWSOrganisationID', <FrozenOrderedDict
515 | OrderedDict([('default', 'o-hdlxtom0dp')])>), ('CentralCloudTrailBucket', <FrozenOrderedDict
516 | OrderedDict([('default', 'centralised-logs-170194364726-eu-west-1')])>), ('CentralConfigBucket',
517 | <FrozenOrderedDict OrderedDict([('default', 'centralised-logs-170194364726-eu-west-1')])>),
518 | ('DeploymentAccountId', <FrozenOrderedDict OrderedDict([('default', '449782587015')])>),
519 | ('GuardDutyAssumableOrgRoleArn', <FrozenOrderedDict OrderedDict([('default', 'arn:aws:iam::178759752866:role/guardduty/GuarDutyAssumableRoleInRootAccount')])>),
520 | ('HubAccountID', <FrozenOrderedDict OrderedDict([('default', '881518331318')])>),
521 | ('HubEnablerFunctionRole', <FrozenOrderedDict OrderedDict([('default', 'arn:aws:iam::881518331318:role/GuardDutyHubRole')])>),
522 | ('LoggingAccountId', <FrozenOrderedDict OrderedDict([('default', '170194364726')])>),
523 | ('MasterAccountId', <FrozenOrderedDict OrderedDict([('default', '178759752866')])>),
524 | ('NetworkAccountId', <FrozenOrderedDict OrderedDict([('default', '280450906216')])>),
525 | ('SSHKeyName', <FrozenOrderedDict OrderedDict([('default', 'SquishyBottom')])>),
526 | ('SecurityAccountId', <FrozenOrderedDict OrderedDict([('default', '881518331318')])>)])>
527 | parameters: []
528 | portfolio: oss-catalog-factory-mandatory-product-portfolio
529 | post_actions: []
530 | pre_actions: []
531 | product: Cloudtrail-Enable
532 | puppet_account_id: '449782587015'
533 | region: eu-west-1
534 | requested_priority: 0
535 | retry_count: 0
536 | should_use_product_plans: true
537 | should_use_sns: true
538 | ssm_param_inputs: []
539 | ssm_param_outputs: []
540 | version: v1
541 | worker_timeout: 0
542 |  
543 | Traceback (most recent call last):
544 |  
545 | File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
546 | new_deps = self._run_get_new_deps()
547 |  
548 | File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 150, in _run_get_new_deps
549 | requires = six.next(task_gen)
550 |  
551 | File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/workflow/provisioning.py", line 309, in run
552 | self.should_use_sns,
553 |  
554 | File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 230, in provision_product_with_plan
555 | raise Exception(f"{uid} :: Plan failed: {response.get('ProvisionedProductPlanDetails').get('StatusMessage')}")
556 |  
557 | Exception: [all-cloudtrail-enable] 109780043335:eu-west-1] :: Plan failed: Error calling API cloudformation:CreateChangeSet. ErrorCode: AlreadyExistsException, Message: ChangeSet SC-109780043335-pp-i6wyicnvqftdo-rec-ag4ukbsrf3udm cannot be created due to a mismatch with existing attribute Template
558
```

**Comment by mckayjuk** [comment]
**Sorry for the delay @nikolaigauss** 

I have just tested behaviour in Puppet version 0.67.3 As follows:
- I changed the description of a Product
- Product Pipeline updated and confirmed the Product in Service Catalog had the newly updated Description
- I re-ran Puppet without making any change
- Puppet ran through successfully without error
- I confirmed:
    - CFN Stack was 'UPDATE_COMPLETE'
    - Provisioned Product was 'AVAILABLE'

I'll DM you for further investigation into your setup

**Comment by nikolaigauss** [comment]
This was fixed by implementing this setting on the SSM parameter: /servicecatalog-puppet/config --> should_use_product_plans: false
