### ISSUE TITLE
Invalid type for parameter PortfolioId, value: ('port-abc',), type: <class 'tuple'>, valid types: <class 'str'>

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#245]
Got the below error after updating to `0.67.1` on the GenerateShares CodeBuild stage.

```
CreateAssociationsInPythonForPortfolioTask failed
parameters:
  account_id: '12345678910'
  portfolio: core
  region: us-east-1

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()

  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()

  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/workflow/portfoliomanagement.py", line 965, in run
    PrincipalType='IAM'

  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)

  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 559, in _make_api_call
    api_params, operation_model, context=request_context)

  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 607, in _convert_to_request_dict
    api_params, operation_model)

  File "/usr/local/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())

botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter PortfolioId, value: ('port-yydma6br5xabc',), type: <class 'tuple'>, valid types: <class 'str'>
```

**Comment by jordan-evans** [comment]
Fixed  in `0.67.2`
