### ISSUE TITLE
IndexError: list index out of range on provisioning.py line 879

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#257]
Getting the following stack trace:

2020-02-11T09:00:03.421Z Traceback (most recent call last):
2020-02-11T09:00:03.421Z   File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
2020-02-11T09:00:03.421Z     new_deps = self._run_get_new_deps()
2020-02-11T09:00:03.421Z   File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 152, in _run_get_new_deps
2020-02-11T09:00:03.421Z     requires = task_gen.send(next_send)
2020-02-11T09:00:03.421Z   File "/usr/local/lib/python3.8/site-packages/servicecatalog_puppet/workflow/provisioning.py", line 956, in run
2020-02-11T09:00:03.421Z     yield self.generate_tasks(tasks_defs.get('task_defs', []))
2020-02-11T09:00:03.421Z   File "/usr/local/lib/python3.8/site-packages/servicecatalog_puppet/workflow/provisioning.py", line 879, in generate_tasks
2020-02-11T09:00:03.421Z     first_task_def = task_defs[0]
2020-02-11T09:00:03.421Z IndexError: list index out of range

**Comment by eamonnfaherty** [comment]
resolved in 0.70.0
