### ISSUE TITLE
Unable to export the puppet pipeline status

### ISSUE THREAD

**Issue by smuralee** [awslabs/aws-service-catalog-puppet#274]
Puppet version: 0.74.1

# Steps to reproduce
1. Export the status via the CLI
```
servicecatalog-puppet expand manifest.yaml
servicecatalog-puppet list-launches manifest-expanded.yaml --format json > list-launches.json
```

# Expected results
The status should be exported to the json file

# Actual results
```
[Container] 2020/05/26 15:19:50 Running command servicecatalog-puppet list-launches manifest-expanded.yaml --format json > list-launches.json
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.6/bin/servicecatalog-puppet", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 147, in list_launches
    core.list_launches(expanded_manifest, format)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/servicecatalog_puppet/core.py", line 541, in list_launches
    tasks = generate_tasks(f)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/servicecatalog_puppet/core.py", line 155, in generate_tasks
    manifest = manifest_utils.load(f)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/servicecatalog_puppet/manifest_utils.py", line 24, in load
    yaml.safe_load(f.read())
ValueError: I/O operation on closed file.
```

**Comment by eamonnfaherty** [comment]
fixed in 0.75.0
