### ISSUE TITLE
generate-shares fails due to AttributeError: '_FrozenOrderedDict' object has no attribute 'update' when using actions

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#278]
[Container] 2020/06/08 21:12:31 Running command servicecatalog-puppet --info generate-shares manifest-expanded.yaml
INFO MainThread Starting to generate shares for: manifest-expanded.yaml
/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/luigi/parameter.py:286: UserWarning: Parameter "single_account" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.2/bin/servicecatalog-puppet", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/servicecatalog_puppet/cli.py", line 21, in generate_shares
    core.generate_shares(f)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/servicecatalog_puppet/core.py", line 69, in generate_shares
    t = manifest_utils_for_launches.generate_launch_task_defs_for_launch(
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/servicecatalog_puppet/manifest_utils_for_launches.py", line 55, in generate_launch_task_defs_for_launch
    'post_actions': get_actions_from(launch_name, launch_details, 'post', actions, 'launch'),
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/servicecatalog_puppet/manifest_utils.py", line 189, in get_actions_from
    action.update(provision_action)
AttributeError: '_FrozenOrderedDict' object has no attribute 'update'

**Comment by eamonnfaherty** [comment]
fixed in 0.76.1
