### ISSUE TITLE
fail spoke-local-portfolios: unknown parameter sharing_mode 

### ISSUE THREAD

**Issue by aroundble** [awslabs/aws-service-catalog-puppet#322]
Please include a link to your expanded manifest, the full contents of your AWS CodeBuild output (see https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#export-puppet-pipeline-logs)

Please ensure you are using the latest version and have run a validate command on your manifest file see (https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#validate)

# Steps to reproduce
1. Spoke to local portfolios without launch constraints : Success
2. Spoke to local portfolios with launch constraints : Fail (unknown_paramater : sharing_mode, but my manifest file doesn't have that parameter"

spoke-local-portfolios-for-network.yaml
---
spoke-local-portfolios:
  vpc-for-spoke:
    portfolio: portfolio-vpc
    product_generation_method: import
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/MyEndUserRoles
    constraints:
      launch:
        - products: "vpc-*"
          roles:
            - arn:aws:iam::${AWS::AccountId}:role/MyVPCLaunchRole
    deploy_to:
      tags:
        - tag: ou:network
          regions: default_region

# Expected results
Succcess

# Actual results
unknown parameter sharing_mode
-- 
Traceback (most recent call last):
[Container] 2020/11/09 14:03:06 Running command pip install aws-service-catalog-puppet==0.90.1
961 |  
962 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
963 | new_deps = self._run_get_new_deps()
964 |  
965 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/luigi/worker.py", line 152, in _run_get_new_deps
966 | requires = task_gen.send(next_send)
967 |  
968 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/servicecatalog_puppet/workflow/provisioning.py", line 1550, in run
969 | yield self.generate_tasks(task_defs)
970 |  
971 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/servicecatalog_puppet/workflow/provisioning.py", line 1469, in generate_tasks
972 | create_launch_role_constraints_for_portfolio = portfoliomanagement_tasks.CreateLaunchRoleConstraintsForPortfolio(
973 |  
974 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/luigi/task_register.py", line 88, in __call__
975 | param_values = cls.get_param_values(params, args, kwargs)
976 |  
977 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/luigi/task.py", line 413, in get_param_values
978 | raise parameter.UnknownParameterException('%s: unknown parameter %s' % (exc_desc, param_name))
979 |  
980 | luigi.parameter.UnknownParameterException: CreateLaunchRoleConstraintsForPortfolio[args=(), kwargs={'manifest_file_path': 'manifest-expanded.yaml', 'account_id': '####', 'region': 'myregion', 'portfolio': 'portfolio-vpc', 'organization': None, 'portfolio_id': 'port-###', **'sharing_mode': 'ACCOUNT'**, 'cache_invalidator': '2020-11-09 14:03:43.811142', 'launch_constraints': [{'products': 'vpc-*', 'roles': ['arn:aws:iam::${AWS::AccountId}:role/MyVPCLaunchRole']}], 'puppet_account_id': '####', 'should_use_sns': False, 'product_generation_method': 'import'}]: unknown parameter sharing_mode
981 |  
982 |  
983 |  
984 | [Container] 2020/11/09 14:03:55 Command did not exit successfully servicecatalog-puppet --info deploy --num-workers ${NUM_WORKERS} manifest-expanded.yaml exit status 1
985 | [Container] 2020/11/09 14:03:55 Phase complete: BUILD State: FAILED
986 | [Container] 2020/11/09 14:03:55 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-puppet --info deploy --num-workers ${NUM_WORKERS} manifest-expanded.yaml. Reason: exit status 1

**Comment by eamonnfaherty** [comment]
Hi,

Could you please try 0.90.3.

There were a couple of issues around this that have been resolved.

**Comment by eamonnfaherty** [comment]
closing due to inactivity and issue has been resolved in newer version
