### ISSUE TITLE
Service-Catalogue-Puppet: Failing with manaul approval

### ISSUE THREAD

**Issue by rajesh-svim** [awslabs/aws-service-catalog-puppet#356]
I am setting a Service -catalog-puppet pipeline in AWS account and while running the below command for manual approval process

servicecatalog-puppet bootstrap --with-manual-approvals

I am getting the below error. I am using the latest version. 

(py3.7) ra344005@C02XJHH1JG5J awscoderepo_prodaccount % servicecatalog-puppet bootstrap --with-manual-approvals
Starting bootstrap
Creating servicecatalog-puppet-regional
Exception in thread eu-west-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/betterboto/cloudformation.py", line 70, in create_or_update
    **kwargs,
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/botocore/client.py", line 649, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/botocore/client.py", line 697, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Parameters[1].ParameterValue, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

Finished creating servicecatalog-puppet-regional
Creating servicecatalog-puppet
Finished creating servicecatalog-puppet.
You need to clone your newly created repo now and will then need to seed it: 
git clone --config 'credential.helper=!aws codecommit credential-helper $@' --config 'credential.UseHttpPath=true' https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/ServiceCatalogPuppet

Please let me know, what is the root cause for this issue??

I am following the below document
https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/getting_up_and_running.html#before-you-install

**Comment by eamonnfaherty** [comment]
Can I see a copy of your config.yaml please.

**Comment by eamonnfaherty** [comment]
Thanks for the quick reply.  Can you confirm you are running the solution in eu-west-2?

**Comment by rajesh-svim** [comment]
Yes

**Comment by rajesh-svim** [comment]
Hi Eamon,

Rajesh here, I met you in AWS London office with Nick. I am working for Lloyds.

**Comment by eamonnfaherty** [comment]
Hi Rajesh.  Hope you are well! 

Is this an upgrade or a fresh install?

**Comment by rajesh-svim** [comment]
It's a fresh install as a part of new setup in our account

**Comment by eamonnfaherty** [comment]
from your error message I think you may be running an old version of servicecatalog-puppet.  Could you please retry with 0.99.2.

I have just released 0.99.2 after resolving a different issue I found when running through your usecase.

If you still have an issue please email me and we can arrange a quick call.

**Comment by rajesh-svim** [comment]
I am using 0.98.0 version, will try with latest version.

If i use the below documentation still i can use the different version other than latest

https://service-catalog-tools-workshop.com/installation/30-service-catalog-puppet/20-bootstrapping/10-puppet-account.html

**Comment by rajesh-svim** [comment]
Sure Eamon, will try with latest version and let you know

**Comment by rajesh-svim** [comment]
try with latest version but getting the below error

(py3.7) ra344005@C02XJHH1JG5J awscoderepo_prodaccount % servicecatalog-puppet bootstrap --with-manual-approvals
Starting bootstrap
Creating servicecatalog-puppet-regional
Traceback (most recent call last):
  File "/Users/ra344005/venv/py3.7/bin/servicecatalog-puppet", line 8, in <module>
    sys.exit(cli())
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 549, in bootstrap
    core.bootstrap(**parameters)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/servicecatalog_puppet/core.py", line 633, in bootstrap
    scm_skip_creation_of_repo,
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/servicecatalog_puppet/core.py", line 331, in _do_bootstrap
    puppet_version, os.environ.get("AWS_DEFAULT_REGION")
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/servicecatalog_puppet/template_builder/hub/bootstrap_region.py", line 18, in get_template
    t.Parameter("DefaultRegionValue", Default=default_region_value, Type="String")
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/troposphere/__init__.py", line 343, in __init__
    super(AWSDeclaration, self).__init__(title, **kwargs)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/troposphere/__init__.py", line 127, in __init__
    self.__setattr__(k, v)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/troposphere/__init__.py", line 220, in __setattr__
    self._raise_type(name, value, expected_type)
  File "/Users/ra344005/venv/py3.7/lib/python3.7/site-packages/troposphere/__init__.py", line 238, in _raise_type
    expected_type))
TypeError: <class 'troposphere.Parameter'>: DefaultRegionValue.Default is <class 'NoneType'>, expected (<class 'str'>, <class 'int'>, <class 'float'>)

**Comment by rajesh-svim** [comment]
This is config.yaml

regions: [
  'eu-west-2',
]
should_collect_cloudformation_events: false
should_forward_events_to_eventbridge: false
should_forward_failures_to_opscenter: true

**Comment by rajesh-svim** [comment]
Hi Eamon,

Can we have a quick call ??

**Comment by rajesh-svim** [comment]
Eamon,

Can you please help me on this

**Comment by eamonnfaherty** [comment]
This is being managed offline.
