### ISSUE TITLE
Depends_On for Stack missing docu / bug

### ISSUE THREAD

**Issue by Mladen-Trampic-SRB-1989** [awslabs/aws-service-catalog-puppet#407]
Here is the puppet manifest of our Product.
What we have there down is depends_on, which should orchestrate stacks creation in order to have all parameters rewritten.

```yaml
---
accounts:
  -
    account_id: "xxxxxxxxxxxxx"
    default_region: eu-central-1
    regions_enabled:
      - eu-central-1
    tags:
      - "type:target-inet-account"
  -
    account_id: "yyyyyyyyyyyyy"
    default_region: eu-central-1
    regions_enabled:
      - eu-central-1
    tags:
      - "type:core"
      - "type:networking"

 

stacks:
  ccoe-inet-in-controls:
    name: ccoe-inet-in-controls
    deploy_to:
      tags:
        -
          tag: "type:target-inet-account"
          regions: default_region
    version: v1
    capabilities:
      - "CAPABILITY_NAMED_IAM"

 

  ccoe-inet-in-pa10-orchestrator:
    name: ccoe-inet-in-pa10-orchestrator
    deploy_to:
      tags:
        -
          tag: "type:core"
          regions: default_region
        -
          tag: "type:networking"
          regions: default_region
    version: v1
    capabilities:
      - "CAPABILITY_NAMED_IAM"
    parameters:
      ParentVPCStack:
        default: 'pa-10-gwlb'
      OrgID:
        default: 'o-FAKORG'
      MasterAccRoleARN:
        default: 'arn:aws:iam::xxxxxxxxxxxxx:role/GetCIDRLambdaReadOnly'
    outputs:
      ssm:
        - param_name: /PaloAlto/InetInSCEventBus-ARN
          stack_output: InetInSCEventBus

 

  ccoe-inet-in-pa10-orchestrator-event-bridge-ssm-parameter:
    name: ccoe-inet-in-pa10-orchestrator-event-bridge-ssm-parameter
    deploy_to:
      tags:
        -
          tag: "type:target-inet-account"
          regions: default_region
        -
          tag: "type:networking"
          regions: default_region
    version: v1
    parameters:
      EventBusARN:
        ssm:
          name: /PaloAlto/InetInSCEventBus-ARN
    depends_on:
      - name: ccoe-inet-in-pa10-orchestrator
        type: stack
        affinity: account

 

spoke-local-portfolios:
  ccoe-inet-in-pa10:
    portfolio: baseline-optional-network
    product_generation_method: copy
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/AWSCloudFormationStackSetExecutionRole
      - arn:aws:iam::${AWS::AccountId}:role/AdminRIT
      - arn:aws:iam::${AWS::AccountId}:role/Admin
    constraints:
      launch:
        - products: "ccoe-inet-in-pa10"
          roles:
            - arn:aws:iam::${AWS::AccountId}:role/servicecatalog-puppet/PuppetRole
    deploy_to:
      tags:
        - tag: type:target-inet-account
          regions: default_region
```

We have also struggled a bit with getting depends_on working properly.

Solved after revengineering code : 
```Yaml
 depends_on:
      - name: ccoe-inet-in-pa10-orchestrator
        type: stack <-------- was needed
        affinity: account
```

With following:
```Yaml
 depends_on:
      - ccoe-inet-in-pa10-orchestrator
```

We were always hitting error:
```plain
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.**/bin/servicecatalog-puppet", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.7.**/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.**/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.7.**/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.7.**/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.7.**/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.**/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 412, in expand
    manifest_commands.expand(f, **params)
  File "/root/.pyenv/versions/3.7.**/lib/python3.7/site-packages/servicecatalog_puppet/commands/manifest.py", line 49, in expand
    new_manifest = manifest_utils.rewrite_ssm_parameters(new_manifest)
  File "/root/.pyenv/versions/3.7.**/lib/python3.7/site-packages/servicecatalog_puppet/manifest_utils.py", line 240, in rewrite_ssm_parameters
    for output in dependency.get("outputs", {}).get("ssm", []):
AttributeError: 'NoneType' object has no attribute 'get'
```

Think this is bug also, since if it string, it will always be part of "launches" in manifest.

https://github.com/awslabs/aws-service-catalog-puppet/blob/master/servicecatalog_puppet/manifest_utils.py#L203-L219
```python
def rewrite_depends_on(manifest):
    for (
        section_item_name,
        section_name,
    ) in constants.ALL_SECTION_NAME_SINGULAR_AND_PLURAL_LIST:
        for item, details in manifest.get(section_name, {}).items():
            for i in range(len(details.get("depends_on", []))):
                if isinstance(details["depends_on"][i], str):
                    manifest[section_name][item]["depends_on"][i] = dict(
                        name=details["depends_on"][i], type="launch",
                    )
                if isinstance(details["depends_on"][i], dict):
                    if details["depends_on"][i].get(constants.AFFINITY) is None:
                        details["depends_on"][i][constants.AFFINITY] = details[
                            "depends_on"
                        ][i]["type"]
    return manifest
```
# Actual results
Dependencies between stacks working as expected.

**Comment by eamonnfaherty** [comment]
type is a required attribute.  Here are the docs: https://service-catalog-tools-workshop.com/design-considerations/fine-grained-depends-on.html

If you specify a depends on as a string it is for backwards compatibility.  in the past you could only depend on launches and so when you specify it as a string we assume you are depending on a launch.  These get rewritten during the expand manifest command.  you can review your expanded manifest to verify the behaviour.

Please reopen this if you think there is a bug or there is other work needed.

**Comment by Mladen-Trampic-SRB-1989** [comment]
@eamonnfaherty , i think still there is an issue here.

https://github.com/awslabs/aws-service-catalog-puppet/blob/e782f6df5b02ce9beb01c0b6fe4f0e7ce1c3b6b7/servicecatalog_puppet/workflow/apps/app_for_task.py#L6

from where these constants are imported ?

We are now facing issue:

```plain
  File "/root/.pyenv/versions/3.7.**/lib/python3.7/site-packages/servicecatalog_puppet/workflow/apps/app_for_task.py", line 6, in <module>
    import constants
ModuleNotFoundError: No module named 'constants'
```
