### ISSUE TITLE
manifest.properties not being parsed for launch versions

### ISSUE THREAD

**Issue by RobBrazier** [awslabs/aws-service-catalog-puppet#419]
Please include a link to your expanded manifest, the full contents of your AWS CodeBuild output (see https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#export-puppet-pipeline-logs)

When upgrading from 0.97.2 to 0.116.0, the manifest.properties is not parsed correctly - the file worked with the previous version, I'm wondering if it's because on https://github.com/awslabs/aws-service-catalog-puppet/blob/master/servicecatalog_puppet/manifest_utils.py#L81, the configparser .get method is used now, maybe it doesn't accept {} as a default value (althought seems like it's using it as another key rather than default value_

Please ensure you are using the latest version and have run a validate command on your manifest file see (https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#validate)

# Steps to reproduce
1. Upgrade to version 0.116.0
1. Run servicecatalog-puppet-pipeline with a manifest.properties being present with launches version configuration

manifest.properties contents:
```properties
[launches]
config-enable-global.version = v16
# ... etc.
```

# Expected results
manifest.properties parsed successfully

# Actual results
```
INFO MainThread reading manifest.properties
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: '{}'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.10/bin/servicecatalog-puppet", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 419, in expand
    manifest_commands.expand(f, **params)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_puppet/commands/manifest.py", line 25, in expand
    manifest = manifest_utils.load(f, puppet_account_id)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_puppet/manifest_utils.py", line 87, in load
    for name, value in parser.get(constants.LAUNCHES, {}).items():
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option '{}' in section: 'launches'
```

**Comment by RobBrazier** [comment]
Looking at https://docs.python.org/3/library/configparser.html#fallback-values might be able to use `parser.get(constants.LAUNCHES, fallback={})`

**Comment by eamonnfaherty** [comment]
do you have a launch named config-enable-global ? 

If you specify something in your properties file that is not in the launches there is an unhelpful error message.

**Comment by RobBrazier** [comment]
yep, the launches and properties all match up and were working on the older version. I do notice that the line numbers don't match up though, the stacktrace references https://github.com/awslabs/aws-service-catalog-puppet/blob/master/servicecatalog_puppet/manifest_utils.py#L87

**Comment by RobBrazier** [comment]
looks like .get() has to have an 'option' passed in as well as the section, so [has_section()](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.has_section) and [items()](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.items) might be the best bet

**Comment by RobBrazier** [comment]
i'll close this once tested, should be in the next couple hours

**Comment by RobBrazier** [comment]
all good - closing the issue, thanks for the fast resolution!
