### ISSUE TITLE
Validation issue with OUs

### ISSUE THREAD

**Issue by richardmilnerwatts** [awslabs/aws-service-catalog-puppet#442]
Please include a link to your expanded manifest, the full contents of your AWS CodeBuild output (see https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#export-puppet-pipeline-logs)

Please ensure you are using the latest version and have run a validate command on your manifest file see (https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#validate)

# Steps to reproduce

1. Use the overwrite functionality to override a tag for a given OU

```
- ou: 'ou-1234-abcdefgh'
    name: 'MyProjectOU'
    overwrite:
      tags:
        - myTag:false
```

2. Run puppet with validation enabled

# Expected results

Puppet validation completes successfully.

# Actual results

```
[Container] 2021/10/07 14:19:50 Running command servicecatalog-puppet validate manifest.yaml
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.10/bin/servicecatalog-puppet", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 474, in validate
    manifest_commands.validate(f)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_puppet/commands/manifest.py", line 114, in validate
    yamale.validate(schema, data, strict=False)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/yamale/yamale.py", line 43, in validate
    raise YamaleError(results)
yamale.yamale_error.YamaleError: Error validating data with schema '/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_puppet/schema.yaml'
    accounts.3.account_id: Required field missing
    accounts.3.default_region: Required field missing
    accounts.3.regions_enabled: Required field missing
    accounts.3.tags: Required field missing
    accounts.3.account_id: Required field missing
    accounts.3.account_id: Required field missing
    accounts.3.append: Required field missing
    accounts.3.default_region: Required field missing
    accounts.3.regions_enabled: Required field missing
    accounts.3.tags: Required field missing

[Container] 2021/10/07 14:19:51 Command did not exit successfully servicecatalog-puppet validate manifest.yaml exit status 1
```

**Comment by eamonnfaherty** [comment]
I cannot reproduce this.  From looking at your snippet it looks like your YAML indentation may be a little off.

**Comment by eamonnfaherty** [comment]
closing due to inactivity.
