### ISSUE TITLE
Error: ThrottlingException when running Puppet

### ISSUE THREAD

**Issue by manavyad** [awslabs/aws-service-catalog-puppet#530]
Hi, 

We are frequently getting a throttling exception when running puppet in customer environment. To resolve this, we have rerun the factory and puppet again, which eliminates the error and the puppet is successfully executed. However, we get the same error "Error: ThrottlingException" when the puppet is executed after a few runs/ days. 

I will share the logs and the manifest file via email. We have also reviewed this post (https://github.com/awslabs/aws-service-catalog-factory/issues/218 ) to eliminate this error.

Sample error:

```
INFO MainThread Sending failure to opscenter: SharePortfolioViaOrgsTask failed: None - None - us-east-2
--
18952 | SharePortfolioViaOrgsTask failed
18953 | parameters:
18954 | manifest_file_path: manifest-expanded.yaml
18955 | ou_to_share_with: ou-1xx1-XXXXXXX
18956 | portfolio: aac-shared
18957 | puppet_account_id: '88202XXXXXX'
18958 | region: us-east-2
18959 |  
18960 | Traceback (most recent call last):
18961 |  
18962 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/luigi/worker.py", line 191, in run
18963 | new_deps = self._run_get_new_deps()
18964 |  
18965 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/luigi/worker.py", line 133, in _run_get_new_deps
18966 | task_gen = self.task.run()
18967 |  
18968 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/workflow/portfolio/sharing_management/share_portfolio_via_orgs_task.py", line 76, in run
18969 | raise Exception(yaml.safe_dump(response.get("ShareDetails")))
18970 |  
18971 | Exception: ShareErrors:
18972 | - Accounts:
18973 | - ou-1xx1-XXXXX
18974 | Error: ThrottlingException
18975 | Message: Can't complete your request. Try again later
18976 | SuccessfulShares: []
18977 |  
18978 |  
18979 |  
18980 |  
18981 | [Container] 2022/07/06 13:53:43 Command did not exit successfully servicecatalog-puppet --info deploy --num-workers ${NUM_WORKERS} manifest-expanded.yaml exit status 1
18982 | [Container] 2022/07/06 13:53:43 Phase complete: BUILD State: FAILED
18983 | [Container] 2022/07/06 13:53:43 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-puppet --info deploy --num-workers ${NUM_WORKERS} manifest-expanded.yaml. Reason: exit status 1
18984 | [Container] 2022/07/06 13:53:43 Entering phase POST_BUILD
```

Regards
Manav

**Comment by eamonnfaherty** [comment]
Thanks for reporting this.

Could you please share a copy of your logs.

**Comment by manavyad** [comment]
Logs Sent via email

**Comment by manavyad** [comment]
Hi Eamon,

 

Happy Thursday!

 

Do you have an update on this issue?

 

Regards

Manav

 

From: "Yadav, Manav" ***@***.***>
Date: Thursday, 7 July 2022 at 11:05
To: awslabs/aws-service-catalog-puppet ***@***.***>
Cc: Author ***@***.***>, "Bhadra, Debojit" ***@***.***>
Subject: Re: [awslabs/aws-service-catalog-puppet] Error: ThrottlingException when running Puupet (Issue #530)

 

Hi Eamon,

 

I have raised an issue in Github with respect to Throttling Exception error that we sometimes get when running puppet. The workaround for this has been rerunning the factory and then puppet which eliminates this error but it is occurring frequently now. Please see attached manifest file and log. 

 

Please let me know if you need further details.

 

Regards

Manav

 

From: Eamonn Faherty ***@***.***>
Reply to: awslabs/aws-service-catalog-puppet ***@***.***>
Date: Thursday, 7 July 2022 at 11:02
To: awslabs/aws-service-catalog-puppet ***@***.***>
Cc: "Yadav, Manav" ***@***.***>, Author ***@***.***>
Subject: Re: [awslabs/aws-service-catalog-puppet] Error: ThrottlingException when running Puupet (Issue #530)

 

Thanks for reporting this.

Could you please share a copy of your logs.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Amazon Web Services EMEA SARL, 38 avenue John F. Kennedy, L-1855 Luxembourg, R.C.S. Luxembourg B186284

Amazon Web Services EMEA Sarl, UK Branch, 1 Principal Place, Worship Street, London, EC2A 2FA, United Kingdom, registered in England and Wales, UK Establishment No. BR019315

**Comment by eamonnfaherty** [comment]
I have not received any logs for this.  Could you ping me them on slack please.

**Comment by manavyad** [comment]
Hi Eamon, 

 

Please see attached.

 

Regards

Manav

 

From: Eamonn Faherty ***@***.***>
Reply to: awslabs/aws-service-catalog-puppet ***@***.***>
Date: Friday, 29 July 2022 at 12:10
To: awslabs/aws-service-catalog-puppet ***@***.***>
Cc: "Yadav, Manav" ***@***.***>, Author ***@***.***>
Subject: Re: [awslabs/aws-service-catalog-puppet] Error: ThrottlingException when running Puppet (Issue #530)

 

I have not received any logs for this. Could you ping me them on slack please.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Amazon Web Services EMEA SARL, 38 avenue John F. Kennedy, L-1855 Luxembourg, R.C.S. Luxembourg B186284

Amazon Web Services EMEA Sarl, UK Branch, 1 Principal Place, Worship Street, London, EC2A 2FA, United Kingdom, registered in England and Wales, UK Establishment No. BR019315

**Comment by eamonnfaherty** [comment]
The task SharePortfolioViaOrgsTask uses the following Service Catalog API calls:
- create_portfolio_share
- describe_portfolio_share_status

Both of these are declared within the api_calls_used method and so the resource management is handled by luigi meaning API throttling exceptions should be avoided.  

Could the Throttling Exception listed be a throttling limit on the number of shares?  Could you please have a look at the CloudTrail object to see what the error was and if there were any other requests within the account at the same time.  It may be worth raising a support ticket with AWS to verify if this was an API throttling limit or a resource throttling limit.

**Comment by eamonnfaherty** [comment]
closing due to inactivity.  this behaviour was rewritten  in 0.186.0  and tested

**Comment by manavyad** [comment]
Hi Eamon,

 

Do you have any update on this? I shared the full log via Slack due to its size.

 

Regards

Manav

 

 

From: "Yadav, Manav" ***@***.***>
Date: Friday, 29 July 2022 at 13:00
To: awslabs/aws-service-catalog-puppet ***@***.***>, awslabs/aws-service-catalog-puppet ***@***.***>, "Faherty, Eamonn" ***@***.***>
Cc: Author ***@***.***>, "Bhadra, Debojit" ***@***.***>
Subject: Re: [awslabs/aws-service-catalog-puppet] Error: ThrottlingException when running Puppet (Issue #530)

 

Hi Eamon, 

 

Please see attached.

 

Regards

Manav

 

From: Eamonn Faherty ***@***.***>
Reply to: awslabs/aws-service-catalog-puppet ***@***.***>
Date: Friday, 29 July 2022 at 12:10
To: awslabs/aws-service-catalog-puppet ***@***.***>
Cc: "Yadav, Manav" ***@***.***>, Author ***@***.***>
Subject: Re: [awslabs/aws-service-catalog-puppet] Error: ThrottlingException when running Puppet (Issue #530)

 

I have not received any logs for this. Could you ping me them on slack please.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Amazon Web Services EMEA SARL, 38 avenue John F. Kennedy, L-1855 Luxembourg, R.C.S. Luxembourg B186284

Amazon Web Services EMEA Sarl, UK Branch, 1 Principal Place, Worship Street, London, EC2A 2FA, United Kingdom, registered in England and Wales, UK Establishment No. BR019315

**Comment by manavyad** [comment]
Hi Eamon,

 

I have raised an issue in Github with respect to Throttling Exception error that we sometimes get when running puppet. The workaround for this has been rerunning the factory and then puppet which eliminates this error but it is occurring frequently now. Please see attached manifest file and log. 

 

Please let me know if you need further details.

 

Regards

Manav

 

From: Eamonn Faherty ***@***.***>
Reply to: awslabs/aws-service-catalog-puppet ***@***.***>
Date: Thursday, 7 July 2022 at 11:02
To: awslabs/aws-service-catalog-puppet ***@***.***>
Cc: "Yadav, Manav" ***@***.***>, Author ***@***.***>
Subject: Re: [awslabs/aws-service-catalog-puppet] Error: ThrottlingException when running Puupet (Issue #530)

 

Thanks for reporting this.

Could you please share a copy of your logs.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Amazon Web Services EMEA SARL, 38 avenue John F. Kennedy, L-1855 Luxembourg, R.C.S. Luxembourg B186284

Amazon Web Services EMEA Sarl, UK Branch, 1 Principal Place, Worship Street, London, EC2A 2FA, United Kingdom, registered in England and Wales, UK Establishment No. BR019315

**Comment by eamonnfaherty** [comment]
have you tried in version 0.186.0 or later?

**Comment by eamonnfaherty** [comment]
the issue should have been reduced in 0.186.0 and will be reduced further in the next release.
