### ISSUE TITLE
Failed to bootstrap spoke for China region

### ISSUE THREAD

**Issue by ganhuang** [awslabs/aws-service-catalog-puppet#540]
# Steps to reproduce
1.  Follow the [guide](https://service-catalog-tools-workshop.com/installation/50-bootstrapping/10-using-cfn-and-codebuild.html#bootstrapping-spokes-in-ou) to bootstrap spoke accounts

# Expected results
bootstrap spoke account in AWS China successfully.

# Actual results
The builder project `servicecatalog-puppet-bootstrap-spokes-in-ou` failed with:

```
[notice] A new release of pip available: 22.1.2 -> 22.2.1
[notice] To update, run: pip install --upgrade pip
[Container] 2022/07/30 11:58:31 Phase complete: INSTALL State: SUCCEEDED
[Container] 2022/07/30 11:58:31 Phase context status code:  Message:
[Container] 2022/07/30 11:58:31 Entering phase PRE_BUILD
[Container] 2022/07/30 11:58:31 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2022/07/30 11:58:31 Phase context status code:  Message:
[Container] 2022/07/30 11:58:31 Entering phase BUILD
[Container] 2022/07/30 11:58:31 Running command servicecatalog-puppet bootstrap-spokes-in-ou $OU_OR_PATH $IAM_ROLE_NAME $IAM_ROLE_ARNS ${OPTIONS}
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.13/bin/servicecatalog-puppet", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 241, in bootstrap_spokes_in_ou
    tag,
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/commands/spoke_management.py", line 131, in bootstrap_spokes_in_ou
    org_iam_role_arn = config.get_org_iam_role_arn(puppet_account_id)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/config.py", line 234, in get_org_iam_role_arn
    region_name=get_home_region(puppet_account_id),
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/config.py", line 222, in get_home_region
    f"{puppet_account_id}-{get_puppet_role_name()}",
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/betterboto/client.py", line 119, in __enter__
    RoleSessionName=self.role_session_name,
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws-cn:sts::01234567890:assumed-role/PuppetDeployRole/AWSCodeBuild-2b767dbe-ff1c-4335-a13f-9b230d8d604e is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::01234567890:role/servicecatalog-puppet/PuppetRole
[Container] 2022/07/30 11:58:32 Command did not exit successfully servicecatalog-puppet bootstrap-spokes-in-ou $OU_OR_PATH $IAM_ROLE_NAME $IAM_ROLE_ARNS ${OPTIONS} exit status 1
[Container] 2022/07/30 11:58:32 Phase complete: BUILD State: FAILED
[Container] 2022/07/30 11:58:32 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-puppet bootstrap-spokes-in-ou $OU_OR_PATH $IAM_ROLE_NAME $IAM_ROLE_ARNS ${OPTIONS}. Reason: exit status 1
[Container] 2022/07/30 11:58:32 Entering phase POST_BUILD
[Container] 2022/07/30 11:58:32 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2022/07/30 11:58:32 Phase context status code:  Message:
[Container] 2022/07/30 11:58:32 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED
[Container] 2022/07/30 11:58:32 Phase context status code:  Message:

```

The partition in AWS China should be `aws-cn` instead of `aws`

```
arn:aws:iam::01234567890:role/servicecatalog-puppet/PuppetRole
```
->

```
arn:aws-cn:iam::01234567890:role/servicecatalog-puppet/PuppetRole
```

**Comment by eamonnfaherty** [comment]
this has been merged. sorry for the delay.
