### ISSUE TITLE
When validating: Puppet 0.193.0 - AttributeError: 'str' object has no attribute 'get' 

### ISSUE THREAD

**Issue by sandrich** [awslabs/aws-service-catalog-puppet#565]
Puppet validate returns the following error

```
267 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/commands/manifest.py", line 280, in validate
268 | dependency.get("type", constants.LAUNCH)
269 | AttributeError: 'str' object has no attribute 'get'
```

Full Log

```


[Container] 2022/09/14 12:02:48 Waiting for agent ping
--
2 | [Container] 2022/09/14 12:02:49 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2022/09/14 12:02:49 Phase is DOWNLOAD_SOURCE
4 | [Container] 2022/09/14 12:02:49 CODEBUILD_SRC_DIR=/codebuild/output/src840428164/src
5 | [Container] 2022/09/14 12:02:49 YAML location is /codebuild/readonly/buildspec.yml
6 | [Container] 2022/09/14 12:02:49 Setting HTTP client timeout to higher timeout for S3 source
7 | [Container] 2022/09/14 12:02:49 Processing environment variables
8 | [Container] 2022/09/14 12:02:49 Selecting 'python' runtime version '3.7' based on manual selections...
9 | [Container] 2022/09/14 12:02:49 Running command echo "Installing Python version 3.7 ..."
10 | Installing Python version 3.7 ...
11 |  
12 | [Container] 2022/09/14 12:02:49 Running command pyenv global  $PYTHON_37_VERSION
13 |  
14 | [Container] 2022/09/14 12:02:51 Moving to directory /codebuild/output/src840428164/src
15 | [Container] 2022/09/14 12:02:51 Configuring ssm agent with target id: codebuild:9cf48c43-9023-462f-8212-6c7f1e6a0bba
16 | [Container] 2022/09/14 12:02:51 Successfully updated ssm agent configuration
17 | [Container] 2022/09/14 12:02:51 Registering with agent
18 | [Container] 2022/09/14 12:02:51 Phases found in YAML: 2
19 | [Container] 2022/09/14 12:02:51  BUILD: 1 commands
20 | [Container] 2022/09/14 12:02:51  INSTALL: 1 commands
21 | [Container] 2022/09/14 12:02:51 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
22 | [Container] 2022/09/14 12:02:51 Phase context status code:  Message:
23 | [Container] 2022/09/14 12:02:51 Entering phase INSTALL
24 | [Container] 2022/09/14 12:02:51 Running command pip install aws-service-catalog-puppet==0.193.0
25 | Collecting aws-service-catalog-puppet==0.193.0
26 | Downloading aws-service-catalog-puppet-0.193.0.tar.gz (138 kB)
27 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.6/138.6 kB 4.7 MB/s eta 0:00:00
28 | Installing build dependencies: started
29 | Installing build dependencies: finished with status 'done'
30 | Getting requirements to build wheel: started
31 | Getting requirements to build wheel: finished with status 'done'
32 | Preparing metadata (pyproject.toml): started
33 | Preparing metadata (pyproject.toml): finished with status 'done'
34 | Collecting PyYAML==5.4
35 | Downloading PyYAML-5.4-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
36 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 636.5/636.5 kB 54.9 MB/s eta 0:00:00
37 | Collecting networkx==2.5
38 | Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
39 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 35.0 MB/s eta 0:00:00
40 | Collecting requests==2.26.0
41 | Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
42 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 17.3 MB/s eta 0:00:00
43 | Requirement already satisfied: Jinja2==2.11.3 in /root/.pyenv/versions/3.7.13/lib/python3.7/site-packages (from aws-service-catalog-puppet==0.193.0) (2.11.3)
44 | Collecting python-daemon==2.1.2
45 | Downloading python_daemon-2.1.2-py2.py3-none-any.whl (19 kB)
46 | Collecting deepdiff==5.3.0
47 | Downloading deepdiff-5.3.0-py3-none-any.whl (64 kB)
48 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 21.7 MB/s eta 0:00:00
49 | Collecting colorclass==2.2.0
50 | Downloading colorclass-2.2.0.tar.gz (17 kB)
51 | Preparing metadata (setup.py): started
52 | Preparing metadata (setup.py): finished with status 'done'
53 | Collecting s3transfer==0.5.0
54 | Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
55 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 kB 22.3 MB/s eta 0:00:00
56 | Collecting deepmerge==0.2.1
57 | Downloading deepmerge-0.2.1-py2.py3-none-any.whl (7.1 kB)
58 | Collecting terminaltables==3.1.0
59 | Downloading terminaltables-3.1.0.tar.gz (12 kB)
60 | Preparing metadata (setup.py): started
61 | Preparing metadata (setup.py): finished with status 'done'
62 | Collecting psutil==5.7.0
63 | Downloading psutil-5.7.0.tar.gz (449 kB)
64 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.6/449.6 kB 58.7 MB/s eta 0:00:00
65 | Preparing metadata (setup.py): started
66 | Preparing metadata (setup.py): finished with status 'done'
67 | Collecting cfn-flip==1.2.3
68 | Downloading cfn_flip-1.2.3.tar.gz (10 kB)
69 | Preparing metadata (setup.py): started
70 | Preparing metadata (setup.py): finished with status 'done'
71 | Collecting six==1.15.0
72 | Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
73 | Collecting charset-normalizer==2.0.7
74 | Downloading charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
75 | Collecting awacs==2.0.2
76 | Downloading awacs-2.0.2-py3-none-any.whl (244 kB)
77 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.8/244.8 kB 45.0 MB/s eta 0:00:00
78 | Collecting better-boto==0.42.0
79 | Downloading better_boto-0.42.0-py3-none-any.whl (13 kB)
80 | Collecting decorator==4.4.2
81 | Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
82 | Collecting click==7.0
83 | Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
84 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 25.9 MB/s eta 0:00:00
85 | Collecting ordered-set==4.0.2
86 | Downloading ordered-set-4.0.2.tar.gz (10 kB)
87 | Preparing metadata (setup.py): started
88 | Preparing metadata (setup.py): finished with status 'done'
89 | Collecting boto3==1.20.5
90 | Downloading boto3-1.20.5-py3-none-any.whl (131 kB)
91 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 kB 34.6 MB/s eta 0:00:00
92 | Collecting typing-extensions==3.10.0.2
93 | Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
94 | Collecting troposphere==3.1.0
95 | Downloading troposphere-3.1.0-py3-none-any.whl (242 kB)
96 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.6/242.6 kB 56.2 MB/s eta 0:00:00
97 | Requirement already satisfied: jmespath==0.10.0 in /root/.pyenv/versions/3.7.13/lib/python3.7/site-packages (from aws-service-catalog-puppet==0.193.0) (0.10.0)
98 | Collecting yamale==3.0.8
99 | Downloading yamale-3.0.8-py3-none-any.whl (51 kB)
100 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.5/51.5 kB 14.8 MB/s eta 0:00:00
101 | Collecting colorama==0.4.5
102 | Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
103 | Collecting luigi==3.0.2
104 | Downloading luigi-3.0.2.tar.gz (1.2 MB)
105 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 88.6 MB/s eta 0:00:00
106 | Preparing metadata (setup.py): started
107 | Preparing metadata (setup.py): finished with status 'done'
108 | Collecting urllib3==1.26.7
109 | Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
110 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.8/138.8 kB 32.5 MB/s eta 0:00:00
111 | Collecting lockfile==0.12.2
112 | Downloading lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
113 | Collecting botocore==1.23.5
114 | Downloading botocore-1.23.5-py3-none-any.whl (8.1 MB)
115 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 108.7 MB/s eta 0:00:00
116 | Collecting docutils==0.15.2
117 | Downloading docutils-0.15.2-py3-none-any.whl (547 kB)
118 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.6/547.6 kB 70.5 MB/s eta 0:00:00
119 | Collecting python-dateutil==2.8.1
120 | Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
121 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.2/227.2 kB 48.3 MB/s eta 0:00:00
122 | Collecting idna==2.8
123 | Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
124 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.6/58.6 kB 18.1 MB/s eta 0:00:00
125 | Collecting certifi==2020.6.20
126 | Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
127 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.6/156.6 kB 37.4 MB/s eta 0:00:00
128 | Collecting tornado==5.1.1
129 | Downloading tornado-5.1.1.tar.gz (516 kB)
130 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.8/516.8 kB 66.7 MB/s eta 0:00:00
131 | Preparing metadata (setup.py): started
132 | Preparing metadata (setup.py): finished with status 'done'
133 | Collecting MarkupSafe==1.1.1
134 | Downloading MarkupSafe-1.1.1-cp37-cp37m-manylinux2010_x86_64.whl (33 kB)
135 | Requirement already satisfied: setuptools in /root/.pyenv/versions/3.7.13/lib/python3.7/site-packages (from python-daemon==2.1.2->aws-service-catalog-puppet==0.193.0) (57.4.0)
136 | Building wheels for collected packages: aws-service-catalog-puppet, cfn-flip, colorclass, luigi, ordered-set, psutil, terminaltables, tornado
137 | Building wheel for aws-service-catalog-puppet (pyproject.toml): started
138 | Building wheel for aws-service-catalog-puppet (pyproject.toml): finished with status 'done'
139 | Created wheel for aws-service-catalog-puppet: filename=aws_service_catalog_puppet-0.193.0-py3-none-any.whl size=250154 sha256=c0462ccc304070f54f15249165ff257cf133bdda5128a6f42fc5fb9e48d8775c
140 | Stored in directory: /root/.cache/pip/wheels/34/01/80/bf066096a014a0bee68f914434c918ac5517423010a031cc60
141 | Building wheel for cfn-flip (setup.py): started
142 | Building wheel for cfn-flip (setup.py): finished with status 'done'
143 | Created wheel for cfn-flip: filename=cfn_flip-1.2.3-py3-none-any.whl size=15150 sha256=9e71c4542d3f0dcb60bc2cdb5519df4405bc68c33626b04db3f724d08e378b82
144 | Stored in directory: /root/.cache/pip/wheels/32/1f/02/56d8fb5d7f876a2583576eab65c91e85ce18a25db6cb667482
145 | Building wheel for colorclass (setup.py): started
146 | Building wheel for colorclass (setup.py): finished with status 'done'
147 | Created wheel for colorclass: filename=colorclass-2.2.0-py3-none-any.whl size=19394 sha256=0c5c468b03b936973bcdc793f9e75923ffbe91b6d601dc8205aaaa438d9849b2
148 | Stored in directory: /root/.cache/pip/wheels/fe/96/67/750617a6039bb687b993830c5852beba03d777e2d5b0b06938
149 | Building wheel for luigi (setup.py): started
150 | Building wheel for luigi (setup.py): finished with status 'done'
151 | Created wheel for luigi: filename=luigi-3.0.2-py3-none-any.whl size=1076750 sha256=2f2c571fa8948159055e2f8075047992bbc278d31b1e6d2129e8c9774922a52b
152 | Stored in directory: /root/.cache/pip/wheels/78/ec/35/5b66c9ff7e8502c7de989e6cc06bdad16967417d13b900e5f8
153 | Building wheel for ordered-set (setup.py): started
154 | Building wheel for ordered-set (setup.py): finished with status 'done'
155 | Created wheel for ordered-set: filename=ordered_set-4.0.2-py2.py3-none-any.whl size=8219 sha256=b70d9f03401c4b44b7db5cf99043435e41205df88881a030cf6719fe80298e56
156 | Stored in directory: /root/.cache/pip/wheels/73/2b/f6/26e9f84153c25050fe7c09e88f8e32a6be3c7034a38c418319
157 | Building wheel for psutil (setup.py): started
158 | Building wheel for psutil (setup.py): finished with status 'done'
159 | Created wheel for psutil: filename=psutil-5.7.0-cp37-cp37m-linux_x86_64.whl size=276701 sha256=a7b005979233ff009205dedc10cab501f0efec385fad32a2150025434402dc61
160 | Stored in directory: /root/.cache/pip/wheels/b6/e7/50/aee9cc966163d74430f13f208171dee22f11efa4a4a826661c
161 | Building wheel for terminaltables (setup.py): started
162 | Building wheel for terminaltables (setup.py): finished with status 'done'
163 | Created wheel for terminaltables: filename=terminaltables-3.1.0-py3-none-any.whl size=15355 sha256=1b2d1aae787caa9b0145f0247e16db625245da78b5d2f4799a564cec0ed00293
164 | Stored in directory: /root/.cache/pip/wheels/ba/ad/c8/2d98360791161cd3db6daf6b5e730f34021fc9367d5879f497
165 | Building wheel for tornado (setup.py): started
166 | Building wheel for tornado (setup.py): finished with status 'done'
167 | Created wheel for tornado: filename=tornado-5.1.1-cp37-cp37m-linux_x86_64.whl size=463321 sha256=7bf905d27ddaa8cd812f6392c81073758e9aee0424042f6d74609ba67bd6bf24
168 | Stored in directory: /root/.cache/pip/wheels/83/91/4b/ee8ffb993d3372fc4129c52c9140792c118dda0373b41e7a8f
169 | Successfully built aws-service-catalog-puppet cfn-flip colorclass luigi ordered-set psutil terminaltables tornado
170 | Installing collected packages: typing-extensions, terminaltables, lockfile, deepmerge, colorclass, certifi, urllib3, tornado, six, PyYAML, psutil, ordered-set, MarkupSafe, idna, docutils, decorator, colorama, click, charset-normalizer, awacs, yamale, requests, python-dateutil, python-daemon, networkx, deepdiff, cfn-flip, troposphere, luigi, botocore, s3transfer, boto3, better-boto, aws-service-catalog-puppet
171 | Attempting uninstall: typing-extensions
172 | Found existing installation: typing-extensions 3.10.0.0
173 | Uninstalling typing-extensions-3.10.0.0:
174 | Successfully uninstalled typing-extensions-3.10.0.0
175 | Attempting uninstall: certifi
176 | Found existing installation: certifi 2022.6.15
177 | Uninstalling certifi-2022.6.15:
178 | Successfully uninstalled certifi-2022.6.15
179 | Attempting uninstall: urllib3
180 | Found existing installation: urllib3 1.26.9
181 | Uninstalling urllib3-1.26.9:
182 | Successfully uninstalled urllib3-1.26.9
183 | Attempting uninstall: six
184 | Found existing installation: six 1.16.0
185 | Uninstalling six-1.16.0:
186 | Successfully uninstalled six-1.16.0
187 | Attempting uninstall: PyYAML
188 | Found existing installation: PyYAML 5.4.1
189 | Uninstalling PyYAML-5.4.1:
190 | Successfully uninstalled PyYAML-5.4.1
191 | Attempting uninstall: MarkupSafe
192 | Found existing installation: MarkupSafe 2.0.1
193 | Uninstalling MarkupSafe-2.0.1:
194 | Successfully uninstalled MarkupSafe-2.0.1
195 | Attempting uninstall: idna
196 | Found existing installation: idna 2.10
197 | Uninstalling idna-2.10:
198 | Successfully uninstalled idna-2.10
199 | Attempting uninstall: docutils
200 | Found existing installation: docutils 0.16
201 | Uninstalling docutils-0.16:
202 | Successfully uninstalled docutils-0.16
203 | Attempting uninstall: colorama
204 | Found existing installation: colorama 0.4.4
205 | Uninstalling colorama-0.4.4:
206 | Successfully uninstalled colorama-0.4.4
207 | Attempting uninstall: click
208 | Found existing installation: click 7.1.2
209 | Uninstalling click-7.1.2:
210 | Successfully uninstalled click-7.1.2
211 | Attempting uninstall: requests
212 | Found existing installation: requests 2.25.1
213 | Uninstalling requests-2.25.1:
214 | Successfully uninstalled requests-2.25.1
215 | Attempting uninstall: python-dateutil
216 | Found existing installation: python-dateutil 2.8.2
217 | Uninstalling python-dateutil-2.8.2:
218 | Successfully uninstalled python-dateutil-2.8.2
219 | Attempting uninstall: botocore
220 | Found existing installation: botocore 1.27.18
221 | Uninstalling botocore-1.27.18:
222 | Successfully uninstalled botocore-1.27.18
223 | Attempting uninstall: s3transfer
224 | Found existing installation: s3transfer 0.6.0
225 | Uninstalling s3transfer-0.6.0:
226 | Successfully uninstalled s3transfer-0.6.0
227 | Attempting uninstall: boto3
228 | Found existing installation: boto3 1.24.18
229 | Uninstalling boto3-1.24.18:
230 | Successfully uninstalled boto3-1.24.18
231 | ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
232 | awscli 1.25.18 requires botocore==1.27.18, but you have botocore 1.23.5 which is incompatible.
233 | awscli 1.25.18 requires colorama<0.4.5,>=0.2.5, but you have colorama 0.4.5 which is incompatible.
234 | awscli 1.25.18 requires s3transfer<0.7.0,>=0.6.0, but you have s3transfer 0.5.0 which is incompatible.
235 | aws-sam-cli 1.52.0 requires click~=7.1, but you have click 7.0 which is incompatible.
236 | aws-sam-cli 1.52.0 requires MarkupSafe==2.0.1, but you have markupsafe 1.1.1 which is incompatible.
237 | aws-sam-cli 1.52.0 requires requests==2.25.1, but you have requests 2.26.0 which is incompatible.
238 | aws-sam-cli 1.52.0 requires typing-extensions==3.10.0.0, but you have typing-extensions 3.10.0.2 which is incompatible.
239 | Successfully installed MarkupSafe-1.1.1 PyYAML-5.4 awacs-2.0.2 aws-service-catalog-puppet-0.193.0 better-boto-0.42.0 boto3-1.20.5 botocore-1.23.5 certifi-2020.6.20 cfn-flip-1.2.3 charset-normalizer-2.0.7 click-7.0 colorama-0.4.5 colorclass-2.2.0 decorator-4.4.2 deepdiff-5.3.0 deepmerge-0.2.1 docutils-0.15.2 idna-2.8 lockfile-0.12.2 luigi-3.0.2 networkx-2.5 ordered-set-4.0.2 psutil-5.7.0 python-daemon-2.1.2 python-dateutil-2.8.1 requests-2.26.0 s3transfer-0.5.0 six-1.15.0 terminaltables-3.1.0 tornado-5.1.1 troposphere-3.1.0 typing-extensions-3.10.0.2 urllib3-1.26.7 yamale-3.0.8
240 | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
241 |  
242 | [notice] A new release of pip available: 22.1.2 -> 22.2.2
243 | [notice] To update, run: pip install --upgrade pip
244 |  
245 | [Container] 2022/09/14 12:03:10 Phase complete: INSTALL State: SUCCEEDED
246 | [Container] 2022/09/14 12:03:10 Phase context status code:  Message:
247 | [Container] 2022/09/14 12:03:10 Entering phase PRE_BUILD
248 | [Container] 2022/09/14 12:03:10 Phase complete: PRE_BUILD State: SUCCEEDED
249 | [Container] 2022/09/14 12:03:10 Phase context status code:  Message:
250 | [Container] 2022/09/14 12:03:10 Entering phase BUILD
251 | [Container] 2022/09/14 12:03:10 Running command servicecatalog-puppet validate manifest.yaml
252 | Traceback (most recent call last):
253 | File "/root/.pyenv/versions/3.7.13/bin/servicecatalog-puppet", line 8, in <module>
254 | sys.exit(cli())
255 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 764, in __call__
256 | return self.main(*args, **kwargs)
257 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 717, in main
258 | rv = self.invoke(ctx)
259 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
260 | return _process_result(sub_ctx.command.invoke(sub_ctx))
261 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 956, in invoke
262 | return ctx.invoke(self.callback, **ctx.params)
263 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 555, in invoke
264 | return callback(*args, **kwargs)
265 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 678, in validate
266 | manifest_commands.validate(f)
267 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/commands/manifest.py", line 280, in validate
268 | dependency.get("type", constants.LAUNCH)
269 | AttributeError: 'str' object has no attribute 'get'
270 |  
271 | [Container] 2022/09/14 12:03:13 Command did not exit successfully servicecatalog-puppet validate manifest.yaml exit status 1
272 | [Container] 2022/09/14 12:03:13 Phase complete: BUILD State: FAILED
273 | [Container] 2022/09/14 12:03:13 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-puppet validate manifest.yaml. Reason: exit status 1
274 | [Container] 2022/09/14 12:03:13 Entering phase POST_BUILD
275 | [Container] 2022/09/14 12:03:13 Phase complete: POST_BUILD State: SUCCEEDED
276 | [Container] 2022/09/14 12:03:13 Phase context status code:  Message:


```

**Comment by eamonnfaherty** [comment]
can you confirm you have a depends on with which is just string and not a dict:

depends_on:
  - some_launch

instead of:

depends_on:
  - name: some_launch
     type: launch

**Comment by sandrich** [comment]
No string. All should be dict.

```
❯ grep -A3 -R deploy_to .
./manifests/security-hub.yaml:    deploy_to:
./manifests/security-hub.yaml-      tags:
./manifests/security-hub.yaml-        - tag: "type:audit"
./manifests/security-hub.yaml-          regions: "default_region"
--
./manifests/security-hub.yaml:    deploy_to:
./manifests/security-hub.yaml-      tags:
./manifests/security-hub.yaml-        - tag: "type:prod"
./manifests/security-hub.yaml-          regions: "default_region"
--
./manifests/config-enable-and-rules:    deploy_to:
./manifests/config-enable-and-rules-      tags:
./manifests/config-enable-and-rules-        - tag: "type:prod"
./manifests/config-enable-and-rules-          regions: "default_region"
--
./manifests/delete-default-network.yaml:    deploy_to:
./manifests/delete-default-network.yaml-      tags:
./manifests/delete-default-network.yaml-        - tag: "type:prod"
./manifests/delete-default-network.yaml-          regions: "default_region"
--
./manifests/account-vending.yaml:    deploy_to:
./manifests/account-vending.yaml-      tags:
./manifests/account-vending.yaml-        - tag: 'role:controltower_management'
./manifests/account-vending.yaml-          regions: default_region
--
./manifests/account-vending.yaml:    deploy_to:
./manifests/account-vending.yaml-      tags:
./manifests/account-vending.yaml-        - tag: 'role:orgs_management'
./manifests/account-vending.yaml-          regions: default_region
--
./manifests/account-vending.yaml:    deploy_to:
./manifests/account-vending.yaml-      tags:
./manifests/account-vending.yaml-        - tag: 'role:sct'
./manifests/account-vending.yaml-          regions: default_region
--
./manifests/account-vending.yaml:    deploy_to:
./manifests/account-vending.yaml-      tags:
./manifests/account-vending.yaml-        - tag: 'role:sct'
./manifests/account-vending.yaml-          regions: default_region
--
./manifests/accounts.yaml:    deploy_to:
./manifests/accounts.yaml-      tags:
./manifests/accounts.yaml-        - tag: "role:sct"
./manifests/accounts.yaml-          regions: "default_region"
--
./manifests/accounts.yaml:    deploy_to:
./manifests/accounts.yaml-      tags:
./manifests/accounts.yaml-        - tag: "role:sct"
./manifests/accounts.yaml-          regions: "default_region"
```

**Comment by eamonnfaherty** [comment]
you have shared the deploy_to and not the depends_on

**Comment by sandrich** [comment]
I should have had a coffee first :D You are correct

```
./security-hub.yaml:    depends_on:
./security-hub.yaml-      - securityhub-master
./security-hub.yaml-    parameters:
./security-hub.yaml-      HubEnablerFunctionRole:
```

Going to change that.

**Comment by eamonnfaherty** [comment]
it is still a bug to be honest.  I am reopening.

**Comment by eamonnfaherty** [comment]
resolved
