### ISSUE TITLE
OpsItemLimitExceededException

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#566]
I get the following error:

Traceback (most recent call last):
--
957 | File "/root/.pyenv/versions/3.7.13/bin/servicecatalog-puppet", line 8, in <module>
958 | sys.exit(cli())
959 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 764, in __call__
960 | return self.main(*args, **kwargs)
961 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 717, in main
962 | rv = self.invoke(ctx)
963 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
964 | return _process_result(sub_ctx.command.invoke(sub_ctx))
965 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 956, in invoke
966 | return ctx.invoke(self.callback, **ctx.params)
967 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 555, in invoke
968 | return callback(*args, **kwargs)
969 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 612, in deploy_from_task_reference
970 | task_reference_commands.deploy_from_task_reference(path)
971 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/commands/task_reference.py", line 1542, in deploy_from_task_reference
972 | running_exploded,
973 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/workflow/runner.py", line 374, in run_tasks
974 | {"Key": "ServiceCatalogPuppet:Actor", "Value": "ops-item"},
975 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
976 | return self._make_api_call(operation_name, kwargs)
977 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
978 | raise error_class(parsed_response, operation_name)
979 | botocore.errorfactory.OpsItemLimitExceededException: An error occurred (OpsItemLimitExceededException) when calling the CreateOpsItem operation: You can specify a maximum of ** Operational Data keys for an OpsItem.

**Comment by eamonnfaherty** [comment]
resolved
