### ISSUE TITLE
PutObject operation: Access Denied for spoke execution mode

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#593]
Stack trace:

Traceback (most recent call last):
--
285 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/threading.py", line 926, in _bootstrap_inner
286 | self.run()
287 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/threading.py", line 870, in run
288 | self._target(*self._args, **self._kwargs)
289 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_puppet/waluigi/threads/topological_generations.py", line 378, in on_task_trace
290 | "args": unwrap(task_params),
291 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
292 | return self._make_api_call(operation_name, kwargs)
293 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
294 | raise error_class(parsed_response, operation_name)
295 | botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

**Comment by eamonnfaherty** [comment]
fixed in https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.205.0
