### ISSUE TITLE
AWS China partition not supported

### ISSUE THREAD

**Issue by tabasku** [awslabs/aws-service-catalog-puppet#617]
When deployed in AWS China partition, service-catalog-puppet command tries to assume role from "aws" partition instead of "aws-cn"

# Steps to reproduce
1. Install Service Catalog Puppet in one of AWS China regions (version 0.209.0)
2. Onboard spoke account
3. Try to deploy product with manifest
4. Deployment fails due assume role being tried to wrong IAM Role arn 

# Expected results

Spoke provisioned with service catalog puppet pipeline

# Actual results

```
[Container] 2022/12/19 08:43:32 Running command servicecatalog-puppet validate manifest.yaml
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.12/bin/servicecatalog-puppet", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/servicecatalog_puppet/cli.py", line 732, in validate
    setup_config()
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/servicecatalog_puppet/cli.py", line 441, in setup_config
    else remote_config.get_regions(puppet_account_id_to_use, home_region_to_use)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/servicecatalog_puppet/remote_config.py", line 122, in get_regions
    return get_config(puppet_account_id, default_region).get(constants.CONFIG_REGIONS)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/servicecatalog_puppet/remote_config.py", line 21, in get_config
    with betterboto_client.CrossAccountClientContextManager(
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/betterboto/client.py", line 117, in __enter__
    assumed_role_object = sts.assume_role(
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws-cn:sts::XXXXXXX:assumed-role/PuppetDeployRole/AWSCodeBuild-ba2c2375-f584-4421-ac07-924a130439c9 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXXXXXX:role/servicecatalog-puppet/PuppetRole
[Container] 2022/12/19 08:43:34 Command did not exit successfully servicecatalog-puppet validate manifest.yaml exit status 1
```

manifest.yml
```
accounts:
  - account_id: "XXXXXXX"
    name: "puppet-account"
    default_region: "cn-north-1"
    regions_enabled:
      - "cn-north-1"
    tags:
      - "type:dev"
      - "partition:cn"
```

**Comment by eamonnfaherty** [comment]
Hi, this has been resolved in version https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.213.0 which will be available in around 15 mins.
