### ISSUE TITLE
Deploy fails because manifest_params is NoneType object

### ISSUE THREAD

**Issue by tv-17** [awslabs/aws-service-catalog-puppet#63]
When running: 

`servicecatalog-puppet --info deploy manifest-expanded.yaml `

If there are no portfolio level parameters in the manifest.yaml file this will result in the error:

```
Traceback (most recent call last): 
  File "/usr/local/bin/servicecatalog-puppet", line 11, in <module> 
    sys.exit(cli()) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__ 
    return self.main(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main 
    rv = self.invoke(ctx) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke 
    return _process_result(sub_ctx.command.invoke(sub_ctx)) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke 
    return callback(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 234, in deploy 
    required_parameters, deployment_map, manifest, launch_details, account_id 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 152, in get_parameters_for_launch 
    manifest_ssm_param = manifest_params.get(required_parameter_name, {}).get('ssm') 
AttributeError: 'NoneType' object has no attribute 'get' 
```

**Comment by eamonnfaherty** [comment]
fixed in 0.1.10
