### ISSUE TITLE
Local Portfolio - Deployment Fails

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#84]
If I try and deploy a local portfolio product with Puppet I get the below error in my pipeline

```
INFO MainThread Getting path for product prod-<id>
Traceback (most recent call last): 
  File "/usr/local/bin/servicecatalog-puppet", line 11, in <module> 
    sys.exit(cli()) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__ 
    return self.main(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main 
    rv = self.invoke(ctx) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke 
    return _process_result(sub_ctx.command.invoke(sub_ctx)) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke 
    return callback(*args, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 27, in deploy 
    cli_commands.deploy(f, single_account) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_commands.py", line 64, in deploy 
    all_launch_tasks = cli_command_helpers.deploy_launches(manifest) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_command_helpers.py", line 498, in deploy_launches 
    all_tasks = deploy_launches_task_builder(deployment_map, manifest, puppet_account_id, section) 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_command_helpers.py", line 517, in deploy_launches_task_builder 
    regional_details, 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli_command_helpers.py", line 538, in deploy_launches_task_builder_for_account_launch_region 
    PathId=aws.get_path_for_product(service_catalog, product_id), 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 204, in get_path_for_product 
    response = service_catalog.list_launch_paths(ProductId=product_id) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the ListLaunchPaths operation: No launch paths found for resource: prod-<id> 
```

I've added the `PuppetRole` as an association to the local portfolio. The target account has no other products deployed to it, and there are no imported portfolios available either.

**Comment by eamonnfaherty** [comment]
This is not supported.  The current design is using launches for puppetrole to provision products into spokes or using import local portfolios to copy products into spokes for the users to provision themselves.
