### ISSUE TITLE
Launch dependencies not working as expected

### ISSUE THREAD

**Issue by nikolaigauss** [awslabs/aws-service-catalog-puppet#86]
When launching a manifests with dependences like this:

```
launch-A:
    portfolio: portfolio-example
    product: Product1
    version: v1
    deploy_to:
      accounts:
      - account_id: *SomeAccountID
        regions: default_region

  launch-B:
    portfolio: portfolio-example
    product: Product2
    version: v1
    depends_on:
      - launch-A
    deploy_to:
      accounts:
      - account_id: *SomeAccountID
        regions: default_region
```

If launch-A fails launch-B will be executed, I believe that the expected outcome is that launch-B gets cancelled, along with other launches depending of launch-A, or launch-B and so on.

**Comment by eamonnfaherty** [comment]
Hi 

Thanks for raising this. 

I will have a look.

**Comment by eamonnfaherty** [comment]
Hi. I hope to have a fix for this tomorrow. Sorry for the delay.

**Comment by eamonnfaherty** [comment]
@nikolaigauss the indent of your manifest looks incorrect.  your accounts section is indented too much.  Is this how you have it in your account?

**Comment by nikolaigauss** [comment]
No it's not, sorry for that, I've just corrected the code in the issue.

**Comment by eamonnfaherty** [comment]
I have tried to recreate this and I cannot.  Here are my logs:


```
INFO: [pid 108] Worker Worker(salt=809916765, workers=10, host=3573f599bd79, username=root, pid=104) running   ProvisionProductTask(launch_name=account-iam-for-spokes-A-2, portfolio=demo-central-it-team-portfolio, product=account-iam, version=v1, product_id=prod-o2c6espnucfs2, version_id=pa-ia4b3iqul7m5w, account_id=0123456789010, region=eu-west-1, puppet_account_id=0123456789010, parameters=[{"name": "RoleName", "value": "MyServiceCatalogAdminRoleForA1"}], ssm_param_inputs=[], dependencies=[], retry_count=1, ssm_param_outputs=[]) 
INFO MainThread [pid 108] Worker Worker(salt=809916765, workers=10, host=3573f599bd79, username=root, pid=104) running   ProvisionProductTask(launch_name=account-iam-for-spokes-A-2, portfolio=demo-central-it-team-portfolio, product=account-iam, version=v1, product_id=prod-o2c6espnucfs2, version_id=pa-ia4b3iqul7m5w, account_id=0123456789010, region=eu-west-1, puppet_account_id=0123456789010, parameters=[{"name": "RoleName", "value": "MyServiceCatalogAdminRoleForA1"}], ssm_param_inputs=[], dependencies=[], retry_count=1, ssm_param_outputs=[]) 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: starting deploy try 1 of 1 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: collecting ssm params 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: collecting manifest params 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: looking for previous failures 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: checking if should be terminated 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Finished waiting for termination 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: provisioned_product_id: False, provisioning_artifact_id : False 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: about to provision with params: {"RoleName": "MyServiceCatalogAdminRoleForA1"} 
INFO MainThread Getting path for product prod-o2c6espnucfs2 
INFO MainThread Got path: lp-pwmkzv63cis6g for product: prod-o2c6espnucfs2 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Creating a plan 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Plan created, waiting for completion 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Waiting for product plan: CREATE_IN_PROGRESS 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Waiting for product plan: CREATE_SUCCESS 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Plan created, changes: - Action: Add 
  Details: [] 
  LogicalResourceId: Role 
  ResourceType: AWS::IAM::Role 
  Scope: [] 
 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: executing changes 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: executing changes for plan: plan-i4rfbvi53uj24 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: waiting for execution to complete: CREATE_SUCCESS 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: waiting for change to complete 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: waiting for change to complete: UNDER_CHANGE 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: waiting for change to complete: UNDER_CHANGE 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: waiting for change to complete: UNDER_CHANGE 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: waiting for change to complete: UNDER_CHANGE 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: waiting for change to complete: UNDER_CHANGE 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: waiting for change to complete: UNDER_CHANGE 
INFO MainThread [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: waiting for change to complete: ERROR 
ERROR: [pid 108] Worker Worker(salt=809916765, workers=10, host=3573f599bd79, username=root, pid=104) failed    ProvisionProductTask(launch_name=account-iam-for-spokes-A-2, portfolio=demo-central-it-team-portfolio, product=account-iam, version=v1, product_id=prod-o2c6espnucfs2, version_id=pa-ia4b3iqul7m5w, account_id=0123456789010, region=eu-west-1, puppet_account_id=0123456789010, parameters=[{"name": "RoleName", "value": "MyServiceCatalogAdminRoleForA1"}], ssm_param_inputs=[], dependencies=[], retry_count=1, ssm_param_outputs=[]) 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run 
    new_deps = self._run_get_new_deps() 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps 
    task_gen = self.task.run() 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 196, in run 
    self.version, 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 187, in provision_product 
    raise Exception(f"[{launch_name}] {account_id}:{region} :: Execute failed: {execute_status}") 
Exception: [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Execute failed: ERROR 
ERROR MainThread [pid 108] Worker Worker(salt=809916765, workers=10, host=3573f599bd79, username=root, pid=104) failed    ProvisionProductTask(launch_name=account-iam-for-spokes-A-2, portfolio=demo-central-it-team-portfolio, product=account-iam, version=v1, product_id=prod-o2c6espnucfs2, version_id=pa-ia4b3iqul7m5w, account_id=0123456789010, region=eu-west-1, puppet_account_id=0123456789010, parameters=[{"name": "RoleName", "value": "MyServiceCatalogAdminRoleForA1"}], ssm_param_inputs=[], dependencies=[], retry_count=1, ssm_param_outputs=[]) 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run 
    new_deps = self._run_get_new_deps() 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps 
    task_gen = self.task.run() 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 196, in run 
    self.version, 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 187, in provision_product 
    raise Exception(f"[{launch_name}] {account_id}:{region} :: Execute failed: {execute_status}") 
Exception: [account-iam-for-spokes-A-2] 0123456789010:eu-west-1 :: Execute failed: ERROR 
INFO: Informed scheduler that task   ProvisionProductTask_0123456789010____account_iam_for__c1c2c9f3b8   has status   FAILED 
INFO MainThread Informed scheduler that task   ProvisionProductTask_0123456789010____account_iam_for__c1c2c9f3b8   has status   FAILED 
INFO: Worker Worker(salt=809916765, workers=10, host=3573f599bd79, username=root, pid=104) was stopped. Shutting down Keep-Alive thread 
INFO Thread-1 Worker Worker(salt=809916765, workers=10, host=3573f599bd79, username=root, pid=104) was stopped. Shutting down Keep-Alive thread 
INFO:  
===== Luigi Execution Summary ===== 
 
Scheduled 2 tasks of which: 
* 1 failed: 
    - 1 ProvisionProductTask(...) 
* 1 were left pending, among these: 
    * 1 had failed dependencies: 
        - 1 ProvisionProductTask(...) 
 
This progress looks :( because there were failed tasks 
 
===== Luigi Execution Summary ===== 
 
INFO MainThread  
===== Luigi Execution Summary ===== 
 
Scheduled 2 tasks of which: 
* 1 failed: 
    - 1 ProvisionProductTask(...) 
* 1 were left pending, among these: 
    * 1 had failed dependencies: 
        - 1 ProvisionProductTask(...) 
 
This progress looks :( because there were failed tasks 
 
===== Luigi Execution Summary ===== 
 
 
[Container] 2019/06/28 14:32:53 Command did not exit successfully servicecatalog-puppet --info deploy manifest-expanded.yaml exit status 1 
[Container] 2019/06/28 14:32:53 Phase complete: BUILD State: FAILED 
[Container] 2019/06/28 14:32:53 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-puppet --info deploy manifest-expanded.yaml. Reason: exit status 1 
[Container] 2019/06/28 14:32:53 Entering phase POST_BUILD 
[Container] 2019/06/28 14:32:53 Phase complete: POST_BUILD State: SUCCEEDED 
[Container] 2019/06/28 14:32:53 Phase context status code:  Message:  
```

And here is my manifest:
```yaml
launches:
  account-iam-for-spokes-A-2:
    portfolio: demo-central-it-team-portfolio
    product: account-iam
    version: v1
    parameters:
      RoleName:
        default: MyServiceCatalogAdminRoleForA1
    deploy_to:
      accounts:
        - account_id: '0123456789010'
          regions: default_region

  account-iam-for-spokes-B-2:
    portfolio: demo-central-it-team-portfolio
    product: account-iam
    version: v1
    parameters:
      RoleName:
        default: MyServiceCatalogAdminRoleForB2
    depends_on:
      - account-iam-for-spokes-A-2
    deploy_to:
      accounts:
        - account_id: '0123456789010'
          regions: default_region

```

Would you be able share your manifest and the whole of your CodeCommit log please

**Comment by eamonnfaherty** [comment]
@nikolaigauss and @jordan-evans I have tried twice now - including using & and * as you have used in your examples.  I cannot get this to fail.

**Comment by eamonnfaherty** [comment]
@nikolaigauss can you confirm which version you are using please?

I will close this in a week or so if I do not hear back.

**Comment by eamonnfaherty** [comment]
closing due to lack of response
